In [1]:
from pathlib import Path
import os

# Run the notebook from the root of your Formula-1 project.
PROJECT_ROOT = Path.cwd().resolve()

# Change this if your spark-warehouse folder is somewhere else.
WAREHOUSE_DIR = PROJECT_ROOT / "spark-warehouse"

print("Project root:", PROJECT_ROOT)
print("Spark warehouse:", WAREHOUSE_DIR)
print("Warehouse exists:", WAREHOUSE_DIR.exists())

Project root: /sfs/gpfs/tardis/home/azd9vv/Formula-1
Spark warehouse: /sfs/gpfs/tardis/home/azd9vv/Formula-1/spark-warehouse
Warehouse exists: True

In [10]:
from pathlib import Path

DATABASE_NAME = "formula1"

PROJECT_ROOT = Path.cwd().resolve()
WAREHOUSE_DIRECTORY = PROJECT_ROOT / "spark-warehouse"
DATABASE_DIRECTORY = WAREHOUSE_DIRECTORY / "formula1.db"

print("Current directory:", PROJECT_ROOT)
print("Warehouse:", WAREHOUSE_DIRECTORY)
print("Database:", DATABASE_DIRECTORY)
print("Database exists:", DATABASE_DIRECTORY.exists())

Current directory: /sfs/gpfs/tardis/home/azd9vv/Formula-1
Warehouse: /sfs/gpfs/tardis/home/azd9vv/Formula-1/spark-warehouse
Database: /sfs/gpfs/tardis/home/azd9vv/Formula-1/spark-warehouse/formula1.db
Database exists: True

In [12]:
if not DATABASE_DIRECTORY.exists():
    raise FileNotFoundError(
        f"Database directory not found: {DATABASE_DIRECTORY}"
    )

table_directories = sorted(
    path
    for path in DATABASE_DIRECTORY.iterdir()
    if path.is_dir()
)

for table_directory in table_directories:
    print(table_directory.name)

drivers
laps
results
session_info
session_status
track_status
weather_data

In [13]:
spark.sql(
    f"""
    CREATE DATABASE IF NOT EXISTS {DATABASE_NAME}
    LOCATION '{DATABASE_DIRECTORY.as_uri()}'
    """
)

spark.sql(f"USE {DATABASE_NAME}")

spark.sql("SELECT current_database()").show()

26/07/10 23:56:41 WARN ObjectStore: Failed to get database formula1, returning NoSuchObjectException
26/07/10 23:56:41 WARN ObjectStore: Failed to get database formula1, returning NoSuchObjectException
26/07/10 23:56:41 WARN ObjectStore: Failed to get database formula1, returning NoSuchObjectException

+----------------+
|current_schema()|
+----------------+
|        formula1|
+----------------+

In [14]:
for table_directory in table_directories:
    table_name = table_directory.name

    if table_name.startswith((".", "_")):
        continue

    storage_format = (
        "DELTA"
        if (table_directory / "_delta_log").exists()
        else "PARQUET"
    )

    try:
        spark.sql(
            f"""
            CREATE TABLE IF NOT EXISTS
                {DATABASE_NAME}.`{table_name}`
            USING {storage_format}
            LOCATION '{table_directory.as_uri()}'
            """
        )

        print(
            f"Registered {DATABASE_NAME}.{table_name} "
            f"using {storage_format}"
        )

    except Exception as error:
        print(f"Could not register {table_name}: {error}")

26/07/10 23:56:48 WARN SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
26/07/10 23:56:49 WARN HiveConf: HiveConf of name hive.internal.ss.authz.settings.applied.marker does not exist

Registered formula1.drivers using PARQUET
Registered formula1.laps using PARQUET
Registered formula1.results using PARQUET
Registered formula1.session_info using PARQUET
Registered formula1.session_status using PARQUET
Registered formula1.track_status using PARQUET
Registered formula1.weather_data using PARQUET

In [15]:
spark.sql("SHOW TABLES IN formula1").show(truncate=False)

+---------+--------------+-----------+
|namespace|tableName     |isTemporary|
+---------+--------------+-----------+
|formula1 |drivers       |false      |
|formula1 |laps          |false      |
|formula1 |results       |false      |
|formula1 |session_info  |false      |
|formula1 |session_status|false      |
|formula1 |track_status  |false      |
|formula1 |weather_data  |false      |
+---------+--------------+-----------+

In [16]:
DATABASE_NAME = "formula1"

if spark.catalog.databaseExists(DATABASE_NAME):
    spark.sql(f"USE {DATABASE_NAME}")
    print(f"Connected to database: {DATABASE_NAME}")
else:
    print(f"Database '{DATABASE_NAME}' was not found.")

Connected to database: formula1

In [17]:
DATABASE_NAME = "formula1"
DATABASE_PATH = WAREHOUSE_DIR / f"{DATABASE_NAME}.db"

spark.sql(f"CREATE DATABASE IF NOT EXISTS {DATABASE_NAME}")
spark.sql(f"USE {DATABASE_NAME}")

required_tables = [
    "results",
    "laps",
    "weather_data",
    "drivers",
    "session_info",
    "session_status",
    "track_status"
]

for table_name in required_tables:
    table_path = DATABASE_PATH / table_name

    if table_path.exists():
        spark.sql(
            f"""
            CREATE TABLE IF NOT EXISTS {DATABASE_NAME}.{table_name}
            USING PARQUET
            LOCATION '{table_path.as_uri()}'
            """
        )

        print(f"Connected: {DATABASE_NAME}.{table_name}")
    else:
        print(f"Not found: {table_path}")

Connected: formula1.results
Connected: formula1.laps
Connected: formula1.weather_data
Connected: formula1.drivers
Connected: formula1.session_info
Connected: formula1.session_status
Connected: formula1.track_status

In [18]:
required_model_tables = [
    "results",
    "laps",
    "weather_data"
]

missing_tables = [
    table_name
    for table_name in required_model_tables
    if not spark.catalog.tableExists(
        f"formula1.{table_name}"
    )
]

if missing_tables:
    raise RuntimeError(
        "Missing required tables: "
        + ", ".join(missing_tables)
    )

print("All required tables are available.")

All required tables are available.

In [19]:
results = spark.table("formula1.results")
laps = spark.table("formula1.laps")
weather_data = spark.table("formula1.weather_data")

print("Results rows:", results.count())
print("Laps rows:", laps.count())
print("Weather rows:", weather_data.count())

Results rows: 5526
Laps rows: 193572
Weather rows: 33398

In [20]:
print("--- RESULTS ---")
results.printSchema()

print("--- LAPS ---")
laps.printSchema()

print("--- WEATHER DATA ---")
weather_data.printSchema()

--- RESULTS ---
root
 |-- DriverNumber: integer (nullable = true)
 |-- BroadcastName: string (nullable = true)
 |-- Abbreviation: string (nullable = true)
 |-- DriverId: string (nullable = true)
 |-- TeamName: string (nullable = true)
 |-- TeamColor: string (nullable = true)
 |-- TeamId: string (nullable = true)
 |-- FirstName: string (nullable = true)
 |-- LastName: string (nullable = true)
 |-- FullName: string (nullable = true)
 |-- HeadshotUrl: string (nullable = true)
 |-- CountryCode: string (nullable = true)
 |-- Position: double (nullable = true)
 |-- ClassifiedPosition: string (nullable = true)
 |-- GridPosition: double (nullable = true)
 |-- Q1: string (nullable = true)
 |-- Q2: string (nullable = true)
 |-- Q3: string (nullable = true)
 |-- Time: string (nullable = true)
 |-- Status: string (nullable = true)
 |-- Points: double (nullable = true)
 |-- Laps: double (nullable = true)
 |-- source_file: string (nullable = true)
 |-- year: integer (nullable = true)
 |-- session_number: integer (nullable = true)
 |-- type_of_race: string (nullable = true)

--- LAPS ---
root
 |-- Time: string (nullable = true)
 |-- Driver: string (nullable = true)
 |-- DriverNumber: integer (nullable = true)
 |-- LapTime: string (nullable = true)
 |-- LapNumber: double (nullable = true)
 |-- Stint: double (nullable = true)
 |-- PitOutTime: string (nullable = true)
 |-- PitInTime: string (nullable = true)
 |-- Sector1Time: string (nullable = true)
 |-- Sector2Time: string (nullable = true)
 |-- Sector3Time: string (nullable = true)
 |-- Sector1SessionTime: string (nullable = true)
 |-- Sector2SessionTime: string (nullable = true)
 |-- Sector3SessionTime: string (nullable = true)
 |-- SpeedI1: double (nullable = true)
 |-- SpeedI2: double (nullable = true)
 |-- SpeedFL: double (nullable = true)
 |-- SpeedST: double (nullable = true)
 |-- IsPersonalBest: boolean (nullable = true)
 |-- Compound: string (nullable = true)
 |-- TyreLife: double (nullable = true)
 |-- FreshTyre: boolean (nullable = true)
 |-- Team: string (nullable = true)
 |-- LapStartTime: string (nullable = true)
 |-- LapStartDate: timestamp (nullable = true)
 |-- TrackStatus: integer (nullable = true)
 |-- Position: double (nullable = true)
 |-- Deleted: boolean (nullable = true)
 |-- DeletedReason: string (nullable = true)
 |-- FastF1Generated: boolean (nullable = true)
 |-- IsAccurate: boolean (nullable = true)
 |-- source_file: string (nullable = true)
 |-- year: integer (nullable = true)
 |-- session_number: integer (nullable = true)
 |-- type_of_race: string (nullable = true)

--- WEATHER DATA ---
root
 |-- Time: string (nullable = true)
 |-- AirTemp: double (nullable = true)
 |-- Humidity: double (nullable = true)
 |-- Pressure: double (nullable = true)
 |-- Rainfall: boolean (nullable = true)
 |-- TrackTemp: double (nullable = true)
 |-- WindDirection: integer (nullable = true)
 |-- WindSpeed: double (nullable = true)
 |-- source_file: string (nullable = true)
 |-- year: integer (nullable = true)
 |-- session_number: integer (nullable = true)
 |-- type_of_race: string (nullable = true)

In [21]:
DATABASE_NAME = "formula1"

spark.sql(f"USE {DATABASE_NAME}")

results = spark.table(f"{DATABASE_NAME}.results")
laps = spark.table(f"{DATABASE_NAME}.laps")
weather = spark.table(f"{DATABASE_NAME}.weather_data")

print("Results:", results.count())
print("Laps:", laps.count())
print("Weather:", weather.count())

Results: 5526
Laps: 193572
Weather: 33398

In [22]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW results_clean AS

SELECT
    CAST(year AS INT) AS year,
    CAST(session_number AS INT) AS session_number,
    UPPER(TRIM(CAST(type_of_race AS STRING))) AS session_type,

    CAST(DriverNumber AS STRING) AS driver_number,

    COALESCE(
        NULLIF(TRIM(CAST(DriverId AS STRING)), ''),
        NULLIF(TRIM(CAST(Abbreviation AS STRING)), ''),
        CAST(DriverNumber AS STRING)
    ) AS driver_id,

    NULLIF(TRIM(CAST(TeamName AS STRING)), '') AS team_name,

    TRY_CAST(Position AS INT) AS result_position,
    TRY_CAST(GridPosition AS INT) AS grid_position,
    TRY_CAST(Points AS DOUBLE) AS championship_points,

    CAST(Status AS STRING) AS status

FROM formula1.results
""")

26/07/11 00:02:35 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

DataFrame[]

In [23]:
spark.sql("""
SELECT
    year,
    session_type,
    COUNT(*) AS rows,
    COUNT(DISTINCT session_number) AS sessions
FROM results_clean
GROUP BY year, session_type
ORDER BY year, session_type
""").show(100)

[Stage 26:>                                                       (0 + 23) / 23]

+----+------------+----+--------+
|year|session_type|rows|sessions|
+----+------------+----+--------+
|2018|           Q| 420|      21|
|2019|           Q| 420|      21|
|2020|           Q| 340|      17|
|2020|           R| 340|      17|
|2021|           Q| 440|      22|
|2021|           R| 440|      22|
|2022|           Q| 440|      22|
|2022|           R| 440|      22|
|2023|           Q|  60|       3|
|2023|           R| 440|      22|
|2024|           R| 479|      24|
|2025|           Q| 480|      24|
|2025|           R| 479|      24|
|2026|           Q| 154|       7|
|2026|           R| 154|       7|
+----+------------+----+--------+

In [25]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW laps_clean AS

SELECT
    CAST(year AS INT) AS year,
    CAST(session_number AS INT) AS session_number,
    UPPER(TRIM(CAST(type_of_race AS STRING))) AS session_type,

    CAST(DriverNumber AS STRING) AS driver_number,
    CAST(Driver AS STRING) AS driver_abbreviation,
    CAST(Team AS STRING) AS team_name,

    TRY_CAST(LapNumber AS INT) AS lap_number,
    TRY_CAST(Position AS DOUBLE) AS running_position,
    TRY_CAST(Stint AS INT) AS stint,

    CAST(Compound AS STRING) AS compound,

    TRY_CAST(SpeedI1 AS DOUBLE) AS speed_i1,
    TRY_CAST(SpeedI2 AS DOUBLE) AS speed_i2,
    TRY_CAST(SpeedFL AS DOUBLE) AS finish_line_speed,
    TRY_CAST(SpeedST AS DOUBLE) AS speed_trap,

    CASE
        WHEN LapTime IS NULL
          OR LOWER(TRIM(CAST(LapTime AS STRING)))
             IN ('', 'nat', 'null', 'none')
        THEN NULL

        ELSE
            COALESCE(
                TRY_CAST(
                    NULLIF(
                        REGEXP_EXTRACT(
                            CAST(LapTime AS STRING),
                            '([0-9]+) days',
                            1
                        ),
                        ''
                    ) AS DOUBLE
                ),
                0
            ) * 86400

            +

            COALESCE(
                TRY_CAST(
                    NULLIF(
                        REGEXP_EXTRACT(
                            CAST(LapTime AS STRING),
                            'days ([0-9]{2}):',
                            1
                        ),
                        ''
                    ) AS DOUBLE
                ),
                0
            ) * 3600

            +

            COALESCE(
                TRY_CAST(
                    NULLIF(
                        REGEXP_EXTRACT(
                            CAST(LapTime AS STRING),
                            'days [0-9]{2}:([0-9]{2}):',
                            1
                        ),
                        ''
                    ) AS DOUBLE
                ),
                0
            ) * 60

            +

            COALESCE(
                TRY_CAST(
                    NULLIF(
                        REGEXP_EXTRACT(
                            CAST(LapTime AS STRING),
                            'days [0-9]{2}:[0-9]{2}:([0-9]+[.]?[0-9]*)',
                            1
                        ),
                        ''
                    ) AS DOUBLE
                ),
                0
            )
    END AS lap_time_seconds

FROM formula1.laps
""")

DataFrame[]

In [26]:
spark.sql("""
SELECT
    year,
    session_number,
    session_type,
    driver_number,
    lap_number,
    lap_time_seconds
FROM laps_clean
WHERE lap_time_seconds IS NOT NULL
ORDER BY year, session_number, driver_number, lap_number
LIMIT 30
""").show()

[Stage 32:==============================>                         (11 + 9) / 20]

+----+--------------+------------+-------------+----------+------------------+
|year|session_number|session_type|driver_number|lap_number|  lap_time_seconds|
+----+--------------+------------+-------------+----------+------------------+
|2018|             1|           Q|           10|         1|             120.4|
|2018|             1|           Q|           10|         2|            85.295|
|2018|             1|           Q|           10|         3|           108.298|
|2018|             1|           Q|           10|         4|            85.425|
|2018|             1|           Q|           10|         6|           117.672|
|2018|             1|           Q|           11|         1|109.61500000000001|
|2018|             1|           Q|           11|         2|            84.914|
|2018|             1|           Q|           11|         3|           111.866|
|2018|             1|           Q|           11|         4|            85.005|
|2018|             1|           Q|           11|         6|           101.179|
|2018|             1|           Q|           11|         7|            84.344|
|2018|             1|           Q|           11|         9|           103.803|
|2018|             1|           Q|           11|        10|             84.28|
|2018|             1|           Q|           11|        12|106.65100000000001|
|2018|             1|           Q|           11|        13|            84.005|
|2018|             1|           Q|           14|         1|           112.786|
|2018|             1|           Q|           14|         2|             84.48|
|2018|             1|           Q|           14|         3|           103.693|
|2018|             1|           Q|           14|         4|            84.244|
|2018|             1|           Q|           14|         6|           105.351|
+----+--------------+------------+-------------+----------+------------------+
only showing top 20 rows

In [27]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW race_outcomes AS

SELECT
    year,
    session_number,
    driver_number,
    driver_id,
    team_name,

    result_position AS target_position,
    championship_points AS target_championship_points,

    grid_position,
    status,

    CASE
        WHEN grid_position > 0
         AND result_position IS NOT NULL
        THEN grid_position - result_position
        ELSE NULL
    END AS positions_gained,

    CASE
        WHEN status IS NULL THEN NULL
        WHEN LOWER(status) = 'finished' THEN 0
        WHEN LOWER(status) LIKE '+%lap%' THEN 0
        ELSE 1
    END AS dnf_flag

FROM results_clean

WHERE session_type = 'R'
  AND result_position IS NOT NULL
""")

DataFrame[]

In [28]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW qualifying_results AS

WITH qualifying AS (
    SELECT
        year,
        session_number,
        driver_number,
        driver_id,
        team_name,
        result_position AS qualifying_position
    FROM results_clean
    WHERE session_type = 'Q'
      AND result_position IS NOT NULL
),

team_windows AS (
    SELECT
        *,

        COUNT(*) OVER (
            PARTITION BY year, session_number
        ) AS qualifying_field_size,

        COUNT(*) OVER (
            PARTITION BY year, session_number, team_name
        ) AS team_driver_count,

        SUM(qualifying_position) OVER (
            PARTITION BY year, session_number, team_name
        ) AS team_position_sum

    FROM qualifying
)

SELECT
    year,
    session_number,
    driver_number,
    driver_id,
    team_name,

    qualifying_position,
    qualifying_field_size,

    CASE
        WHEN qualifying_field_size > 1
        THEN
            (qualifying_position - 1.0)
            / (qualifying_field_size - 1.0)
    END AS qualifying_position_percentile,

    CASE
        WHEN qualifying_position <= 10 THEN 1
        ELSE 0
    END AS qualified_top_10,

    CASE
        WHEN team_driver_count = 2
        THEN team_position_sum - qualifying_position
    END AS teammate_qualifying_position,

    CASE
        WHEN team_driver_count = 2
        THEN
            qualifying_position
            - (team_position_sum - qualifying_position)
    END AS qualifying_vs_teammate

FROM team_windows
""")

DataFrame[]

In [29]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW qualifying_lap_features AS

SELECT
    year,
    session_number,
    driver_number,

    COUNT(lap_time_seconds) AS valid_qualifying_laps,

    MIN(lap_time_seconds) AS best_qualifying_lap,

    PERCENTILE_APPROX(
        lap_time_seconds,
        0.50
    ) AS median_qualifying_lap,

    AVG(lap_time_seconds) AS mean_qualifying_lap,

    STDDEV_SAMP(
        lap_time_seconds
    ) AS qualifying_lap_sd,

    MAX(speed_i1) AS maximum_speed_i1,
    MAX(speed_i2) AS maximum_speed_i2,
    MAX(finish_line_speed) AS maximum_finish_line_speed,
    MAX(speed_trap) AS maximum_speed_trap,

    COUNT(DISTINCT stint) AS qualifying_stints,
    COUNT(DISTINCT compound) AS qualifying_compounds

FROM laps_clean

WHERE session_type = 'Q'
  AND lap_time_seconds BETWEEN 20 AND 400

GROUP BY
    year,
    session_number,
    driver_number
""")

DataFrame[]

In [30]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW qualifying_features AS

WITH combined AS (
    SELECT
        q.*,

        l.valid_qualifying_laps,
        l.best_qualifying_lap,
        l.median_qualifying_lap,
        l.mean_qualifying_lap,
        l.qualifying_lap_sd,

        l.maximum_speed_i1,
        l.maximum_speed_i2,
        l.maximum_finish_line_speed,
        l.maximum_speed_trap,

        l.qualifying_stints,
        l.qualifying_compounds

    FROM qualifying_results q

    LEFT JOIN qualifying_lap_features l
      ON q.year = l.year
     AND q.session_number = l.session_number
     AND q.driver_number = l.driver_number
)

SELECT
    *,

    best_qualifying_lap
    - MIN(best_qualifying_lap) OVER (
        PARTITION BY year, session_number
    ) AS qualifying_gap_to_pole

FROM combined
""")

DataFrame[]

In [31]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW qualifying_weather AS

SELECT
    CAST(year AS INT) AS year,
    CAST(session_number AS INT) AS session_number,

    AVG(TRY_CAST(AirTemp AS DOUBLE)) AS qualifying_air_temperature,
    AVG(TRY_CAST(TrackTemp AS DOUBLE)) AS qualifying_track_temperature,
    AVG(TRY_CAST(Humidity AS DOUBLE)) AS qualifying_humidity,
    AVG(TRY_CAST(Pressure AS DOUBLE)) AS qualifying_pressure,
    AVG(TRY_CAST(WindSpeed AS DOUBLE)) AS qualifying_wind_speed,

    MAX(
        CASE
            WHEN LOWER(TRIM(CAST(Rainfall AS STRING)))
                 IN ('true', '1', '1.0')
            THEN 1
            ELSE 0
        END
    ) AS qualifying_rain

FROM formula1.weather_data

WHERE UPPER(TRIM(CAST(type_of_race AS STRING))) = 'Q'

GROUP BY
    CAST(year AS INT),
    CAST(session_number AS INT)
""")

DataFrame[]

In [32]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW driver_history AS

SELECT
    r.*,

    LAG(target_position, 1) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
    ) AS previous_finish,

    LAG(target_championship_points, 1) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
    ) AS previous_points,

    LAG(dnf_flag, 1) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
    ) AS previous_dnf,

    AVG(target_position) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
        ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING
    ) AS average_finish_last_3,

    AVG(target_position) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
        ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
    ) AS average_finish_last_5,

    STDDEV_SAMP(target_position) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
        ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
    ) AS finish_sd_last_5,

    AVG(COALESCE(target_championship_points, 0.0)) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
        ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
    ) AS average_points_last_5,

    SUM(COALESCE(target_championship_points, 0.0)) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
        ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
    ) AS total_points_last_5,

    AVG(dnf_flag) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
        ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
    ) AS dnf_rate_last_5,

    AVG(positions_gained) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
        ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
    ) AS average_positions_gained_last_5,

    SUM(COALESCE(target_championship_points, 0.0)) OVER (
        PARTITION BY driver_id, year
        ORDER BY session_number
        ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
    ) AS season_points_before_race,

    COUNT(*) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
        ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
    ) AS career_races_before

FROM race_outcomes r
""")

DataFrame[]

In [33]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW qualifying_history AS

SELECT
    q.*,

    AVG(qualifying_position) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
        ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING
    ) AS average_qualifying_position_last_3,

    AVG(qualifying_position) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
        ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
    ) AS average_qualifying_position_last_5,

    AVG(qualifying_gap_to_pole) OVER (
        PARTITION BY driver_id
        ORDER BY year, session_number
        ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
    ) AS average_gap_to_pole_last_5

FROM qualifying_features q
""")

DataFrame[]

In [34]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW team_race_results AS

SELECT
    year,
    session_number,
    team_name,

    AVG(target_position) AS team_event_average_finish,

    SUM(
        COALESCE(target_championship_points, 0.0)
    ) AS team_event_points,

    AVG(dnf_flag) AS team_event_dnf_rate

FROM race_outcomes

WHERE team_name IS NOT NULL

GROUP BY
    year,
    session_number,
    team_name
""")

DataFrame[]

In [35]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW team_history AS

SELECT
    t.*,

    AVG(team_event_average_finish) OVER (
        PARTITION BY team_name
        ORDER BY year, session_number
        ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING
    ) AS team_average_finish_last_3,

    AVG(team_event_average_finish) OVER (
        PARTITION BY team_name
        ORDER BY year, session_number
        ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
    ) AS team_average_finish_last_5,

    AVG(team_event_points) OVER (
        PARTITION BY team_name
        ORDER BY year, session_number
        ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
    ) AS team_average_points_last_5,

    AVG(team_event_dnf_rate) OVER (
        PARTITION BY team_name
        ORDER BY year, session_number
        ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING
    ) AS team_dnf_rate_last_5

FROM team_race_results t
""")

DataFrame[]

In [36]:
modeling_df = spark.sql("""
SELECT
    d.year,
    d.session_number,

    d.driver_number,
    d.driver_id,
    d.team_name,

    q.qualifying_position,
    q.qualifying_field_size,
    q.qualifying_position_percentile,
    q.qualified_top_10,
    q.teammate_qualifying_position,
    q.qualifying_vs_teammate,

    q.valid_qualifying_laps,
    q.best_qualifying_lap,
    q.median_qualifying_lap,
    q.mean_qualifying_lap,
    q.qualifying_lap_sd,
    q.qualifying_gap_to_pole,

    q.maximum_speed_i1,
    q.maximum_speed_i2,
    q.maximum_finish_line_speed,
    q.maximum_speed_trap,

    q.qualifying_stints,
    q.qualifying_compounds,

    q.average_qualifying_position_last_3,
    q.average_qualifying_position_last_5,
    q.average_gap_to_pole_last_5,

    w.qualifying_air_temperature,
    w.qualifying_track_temperature,
    w.qualifying_humidity,
    w.qualifying_pressure,
    w.qualifying_wind_speed,
    w.qualifying_rain,

    d.previous_finish,
    d.previous_points,
    d.previous_dnf,

    d.average_finish_last_3,
    d.average_finish_last_5,
    d.finish_sd_last_5,

    d.average_points_last_5,
    d.total_points_last_5,
    d.dnf_rate_last_5,
    d.average_positions_gained_last_5,

    d.season_points_before_race,
    d.career_races_before,

    t.team_average_finish_last_3,
    t.team_average_finish_last_5,
    t.team_average_points_last_5,
    t.team_dnf_rate_last_5,

    d.target_position,
    d.target_championship_points

FROM driver_history d

INNER JOIN qualifying_history q
  ON d.year = q.year
 AND d.session_number = q.session_number
 AND d.driver_number = q.driver_number

LEFT JOIN qualifying_weather w
  ON d.year = w.year
 AND d.session_number = w.session_number

LEFT JOIN team_history t
  ON d.year = t.year
 AND d.session_number = t.session_number
 AND d.team_name = t.team_name
""")

In [37]:
print("Rows:", modeling_df.count())
print("Columns:", len(modeling_df.columns))

modeling_df.printSchema()

Rows: 1906
Columns: 50
root
 |-- year: integer (nullable = true)
 |-- session_number: integer (nullable = true)
 |-- driver_number: string (nullable = true)
 |-- driver_id: string (nullable = true)
 |-- team_name: string (nullable = true)
 |-- qualifying_position: integer (nullable = true)
 |-- qualifying_field_size: long (nullable = false)
 |-- qualifying_position_percentile: decimal(36,24) (nullable = true)
 |-- qualified_top_10: integer (nullable = false)
 |-- teammate_qualifying_position: long (nullable = true)
 |-- qualifying_vs_teammate: long (nullable = true)
 |-- valid_qualifying_laps: long (nullable = true)
 |-- best_qualifying_lap: double (nullable = true)
 |-- median_qualifying_lap: double (nullable = true)
 |-- mean_qualifying_lap: double (nullable = true)
 |-- qualifying_lap_sd: double (nullable = true)
 |-- qualifying_gap_to_pole: double (nullable = true)
 |-- maximum_speed_i1: double (nullable = true)
 |-- maximum_speed_i2: double (nullable = true)
 |-- maximum_finish_line_speed: double (nullable = true)
 |-- maximum_speed_trap: double (nullable = true)
 |-- qualifying_stints: long (nullable = true)
 |-- qualifying_compounds: long (nullable = true)
 |-- average_qualifying_position_last_3: double (nullable = true)
 |-- average_qualifying_position_last_5: double (nullable = true)
 |-- average_gap_to_pole_last_5: double (nullable = true)
 |-- qualifying_air_temperature: double (nullable = true)
 |-- qualifying_track_temperature: double (nullable = true)
 |-- qualifying_humidity: double (nullable = true)
 |-- qualifying_pressure: double (nullable = true)
 |-- qualifying_wind_speed: double (nullable = true)
 |-- qualifying_rain: integer (nullable = true)
 |-- previous_finish: integer (nullable = true)
 |-- previous_points: double (nullable = true)
 |-- previous_dnf: integer (nullable = true)
 |-- average_finish_last_3: double (nullable = true)
 |-- average_finish_last_5: double (nullable = true)
 |-- finish_sd_last_5: double (nullable = true)
 |-- average_points_last_5: double (nullable = true)
 |-- total_points_last_5: double (nullable = true)
 |-- dnf_rate_last_5: double (nullable = true)
 |-- average_positions_gained_last_5: double (nullable = true)
 |-- season_points_before_race: double (nullable = true)
 |-- career_races_before: long (nullable = false)
 |-- team_average_finish_last_3: double (nullable = true)
 |-- team_average_finish_last_5: double (nullable = true)
 |-- team_average_points_last_5: double (nullable = true)
 |-- team_dnf_rate_last_5: double (nullable = true)
 |-- target_position: integer (nullable = true)
 |-- target_championship_points: double (nullable = true)

In [38]:
modeling_df.orderBy(
    "year",
    "session_number",
    "target_position"
).show(30, truncate=False)

+----+--------------+-------------+---------------+-----------------+-------------------+---------------------+------------------------------+----------------+----------------------------+----------------------+---------------------+-------------------+---------------------+-------------------+------------------+----------------------+----------------+----------------+-------------------------+------------------+-----------------+--------------------+----------------------------------+----------------------------------+--------------------------+--------------------------+----------------------------+-------------------+-------------------+---------------------+---------------+---------------+---------------+------------+---------------------+---------------------+----------------+---------------------+-------------------+---------------+-------------------------------+-------------------------+-------------------+--------------------------+--------------------------+--------------------------+--------------------+---------------+--------------------------+
|year|session_number|driver_number|driver_id      |team_name        |qualifying_position|qualifying_field_size|qualifying_position_percentile|qualified_top_10|teammate_qualifying_position|qualifying_vs_teammate|valid_qualifying_laps|best_qualifying_lap|median_qualifying_lap|mean_qualifying_lap|qualifying_lap_sd |qualifying_gap_to_pole|maximum_speed_i1|maximum_speed_i2|maximum_finish_line_speed|maximum_speed_trap|qualifying_stints|qualifying_compounds|average_qualifying_position_last_3|average_qualifying_position_last_5|average_gap_to_pole_last_5|qualifying_air_temperature|qualifying_track_temperature|qualifying_humidity|qualifying_pressure|qualifying_wind_speed|qualifying_rain|previous_finish|previous_points|previous_dnf|average_finish_last_3|average_finish_last_5|finish_sd_last_5|average_points_last_5|total_points_last_5|dnf_rate_last_5|average_positions_gained_last_5|season_points_before_race|career_races_before|team_average_finish_last_3|team_average_finish_last_5|team_average_points_last_5|team_dnf_rate_last_5|target_position|target_championship_points|
+----+--------------+-------------+---------------+-----------------+-------------------+---------------------+------------------------------+----------------+----------------------------+----------------------+---------------------+-------------------+---------------------+-------------------+------------------+----------------------+----------------+----------------+-------------------------+------------------+-----------------+--------------------+----------------------------------+----------------------------------+--------------------------+--------------------------+----------------------------+-------------------+-------------------+---------------------+---------------+---------------+---------------+------------+---------------------+---------------------+----------------+---------------------+-------------------+---------------+-------------------------------+-------------------------+-------------------+--------------------------+--------------------------+--------------------------+--------------------+---------------+--------------------------+
|2020|1             |77           |bottas         |Mercedes         |1                  |20                   |0.000000000000000000000000    |1               |2                           |-1                    |12                   |62.939             |81.533               |76.14608333333334  |11.782654905783666|0.0                   |323.0           |253.0           |289.0                    |321.0             |6                |1                   |2.6666666666666665                |3.4                               |0.2748000000000019        |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |1              |25.0                      |
|2020|1             |16           |leclerc        |Ferrari          |7                  |20                   |0.315789473684210526315789    |1               |11                          |-4                    |13                   |63.923             |64.995               |74.71161538461537  |12.028541540425573|0.9840000000000018    |314.0           |252.0           |286.0                    |312.0             |6                |1                   |4.0                               |3.2                               |0.24560000000000173       |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |2              |18.0                      |
|2020|1             |4            |norris         |McLaren          |4                  |20                   |0.157894736842105263157895    |1               |8                           |-4                    |10                   |63.626             |74.706               |76.68239999999999  |13.047172364581957|0.6869999999999976    |322.0           |252.0           |290.0                    |320.0             |6                |1                   |8.666666666666666                 |8.4                               |1.4264000000000039        |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |3              |16.0                      |
|2020|1             |44           |hamilton       |Mercedes         |2                  |20                   |0.052631578947368421052632    |1               |1                           |1                     |14                   |62.951             |65.071               |74.47285714285715  |11.824329682462363|0.012000000000000455  |323.0           |252.0           |291.0                    |322.0             |6                |1                   |3.0                               |3.4                               |0.2460000000000008        |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |4              |12.0                      |
|2020|1             |55           |sainz          |McLaren          |8                  |20                   |0.368421052631578947368421    |1               |4                           |4                     |11                   |63.971000000000004 |64.951               |74.01290909090909  |11.346382652233665|1.0320000000000036    |319.0           |251.0           |291.0                    |318.0             |5                |1                   |12.0                              |10.0                              |3.850400000000005         |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |5              |10.0                      |
|2020|1             |11           |perez          |Racing Point     |6                  |20                   |0.263157894736842105263158    |1               |9                           |-3                    |12                   |63.86              |69.803               |74.65641666666667  |10.496029071279837|0.9209999999999994    |323.0           |249.0           |289.0                    |321.0             |6                |1                   |15.0                              |14.6                              |2.5403999999999995        |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |6              |8.0                       |
|2020|1             |10           |gasly          |AlphaTauri       |12                 |20                   |0.578947368421052631578947    |0               |13                          |-1                    |10                   |64.305             |65.99                |76.92520000000002  |12.95921672701625 |1.3660000000000068    |318.0           |248.0           |289.0                    |316.0             |4                |1                   |9.666666666666666                 |9.6                               |1.7294000000000012        |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |7              |6.0                       |
|2020|1             |31           |ocon           |Renault          |14                 |20                   |0.684210526315789473684211    |0               |10                          |4                     |8                    |64.643             |65.019               |73.583375          |9.777125927935788 |1.7040000000000006    |318.0           |249.0           |289.0                    |315.0             |4                |1                   |11.0                              |9.4                               |1.6827999999999974        |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |8              |4.0                       |
|2020|1             |99           |giovinazzi     |Alfa Romeo Racing|18                 |20                   |0.894736842105263157894737    |0               |19                          |-1                    |5                    |65.175             |81.806               |75.6532            |9.444231450996954 |2.235999999999997     |325.0           |246.0           |289.0                    |320.0             |3                |1                   |15.333333333333334                |14.4                              |2.329800000000006         |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |9              |2.0                       |
|2020|1             |5            |vettel         |Ferrari          |11                 |20                   |0.526315789473684210526316    |0               |7                           |4                     |9                    |64.206             |74.30199999999999    |79.66633333333334  |18.39493526082655 |1.267000000000003     |314.0           |250.0           |287.0                    |313.0             |4                |1                   |3.0                               |2.6                               |0.2224000000000018        |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |10             |1.0                       |
|2020|1             |6            |latifi         |Williams         |20                 |20                   |1.000000000000000000000000    |0               |17                          |3                     |10                   |65.757             |67.208               |76.62800000000001  |11.133079188716044|2.818000000000005     |317.0           |243.0           |286.0                    |313.0             |2                |1                   |NULL                              |NULL                              |NULL                      |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |11             |0.0                       |
|2020|1             |26           |kvyat          |AlphaTauri       |13                 |20                   |0.631578947368421052631579    |0               |12                          |1                     |10                   |64.431             |65.658               |79.177             |19.019136316410954|1.4919999999999973    |319.0           |250.0           |289.0                    |317.0             |4                |1                   |14.333333333333334                |13.2                              |2.028999999999999         |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |12             |0.0                       |
|2020|1             |23           |albon          |Red Bull Racing  |5                  |20                   |0.210526315789473684210526    |1               |3                           |2                     |12                   |63.746             |64.853               |75.224             |12.106067502027084|0.8070000000000022    |320.0           |255.0           |289.0                    |319.0             |5                |1                   |6.0                               |5.8                               |0.6438000000000045        |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |13             |0.0                       |
|2020|1             |7            |raikkonen      |Alfa Romeo Racing|19                 |20                   |0.947368421052631578947368    |0               |18                          |1                     |6                    |65.224             |65.569               |76.64049999999999  |12.496981631578079|2.2850000000000037    |323.0           |244.0           |288.0                    |320.0             |3                |1                   |14.666666666666666                |14.2                              |2.360400000000007         |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |14             |0.0                       |
|2020|1             |63           |russell        |Williams         |17                 |20                   |0.842105263157894736842105    |0               |20                          |-3                    |8                    |65.167             |65.592               |79.7465            |18.24191827318921 |2.2280000000000015    |322.0           |246.0           |288.0                    |318.0             |2                |1                   |18.333333333333332                |18.4                              |3.453800000000007         |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL            |NULL                 |NULL               |NULL           |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |15             |0.0                       |

In [39]:
duplicate_rows = (
    modeling_df
    .groupBy(
        "year",
        "session_number",
        "driver_number"
    )
    .count()
    .filter("count > 1")
)

duplicate_rows.show(truncate=False)

+----+--------------+-------------+-----+
|year|session_number|driver_number|count|
+----+--------------+-------------+-----+
+----+--------------+-------------+-----+

In [40]:
from pyspark.sql import functions as F

missing_counts = modeling_df.select(
    *[
        F.sum(
            F.col(column).isNull().cast("int")
        ).alias(column)
        for column in modeling_df.columns
    ]
)

missing_counts.show(truncate=False, vertical=True)

-RECORD 0---------------------------------
 year                               | 0
 session_number                     | 0
 driver_number                      | 0
 driver_id                          | 0
 team_name                          | 0
 qualifying_position                | 0
 qualifying_field_size              | 0
 qualifying_position_percentile     | 0
 qualified_top_10                   | 0
 teammate_qualifying_position       | 5
 qualifying_vs_teammate             | 5
 valid_qualifying_laps              | 11
 best_qualifying_lap                | 11
 median_qualifying_lap              | 11
 mean_qualifying_lap                | 11
 qualifying_lap_sd                  | 21
 qualifying_gap_to_pole             | 11
 maximum_speed_i1                   | 11
 maximum_speed_i2                   | 11
 maximum_finish_line_speed          | 13
 maximum_speed_trap                 | 11
 qualifying_stints                  | 11
 qualifying_compounds               | 11
 average_qualifying_position_last_3 | 18
 average_qualifying_position_last_5 | 18
 average_gap_to_pole_last_5         | 19
 qualifying_air_temperature         | 0
 qualifying_track_temperature       | 0
 qualifying_humidity                | 0
 qualifying_pressure                | 0
 qualifying_wind_speed              | 0
 qualifying_rain                    | 0
 previous_finish                    | 36
 previous_points                    | 36
 previous_dnf                       | 36
 average_finish_last_3              | 36
 average_finish_last_5              | 36
 finish_sd_last_5                   | 72
 average_points_last_5              | 36
 total_points_last_5                | 36
 dnf_rate_last_5                    | 36
 average_positions_gained_last_5    | 36
 season_points_before_race          | 126
 career_races_before                | 0
 team_average_finish_last_3         | 32
 team_average_finish_last_5         | 32
 team_average_points_last_5         | 32
 team_dnf_rate_last_5               | 32
 target_position                    | 0
 target_championship_points         | 0

In [74]:
modeling_df.groupBy("year").agg(
    F.count("*").alias("rows"),
    F.countDistinct("session_number").alias("races"),
    F.countDistinct("driver_id").alias("drivers")
).orderBy("year").show()

+----+----+-----+-------+
|year|rows|races|drivers|
+----+----+-----+-------+
|2020| 340|   17|     23|
|2021| 438|   22|     21|
|2022| 439|   22|     22|
|2023|  60|    3|     20|
|2025| 478|   24|     21|
|2026| 151|    7|     22|
+----+----+-----+-------+

In [75]:
spark.sql("""
CREATE OR REPLACE TEMP VIEW race_weather AS

SELECT
    CAST(year AS INT) AS year,
    CAST(session_number AS INT) AS session_number,

    AVG(
        TRY_CAST(AirTemp AS DOUBLE)
    ) AS race_air_temperature,

    AVG(
        TRY_CAST(TrackTemp AS DOUBLE)
    ) AS race_track_temperature,

    AVG(
        TRY_CAST(Humidity AS DOUBLE)
    ) AS race_humidity,

    AVG(
        TRY_CAST(Pressure AS DOUBLE)
    ) AS race_pressure,

    AVG(
        TRY_CAST(WindSpeed AS DOUBLE)
    ) AS race_wind_speed,

    MAX(
        TRY_CAST(WindSpeed AS DOUBLE)
    ) AS race_max_wind_speed,

    MIN(
        TRY_CAST(AirTemp AS DOUBLE)
    ) AS race_min_air_temperature,

    MAX(
        TRY_CAST(AirTemp AS DOUBLE)
    ) AS race_max_air_temperature,

    MAX(
        CASE
            WHEN LOWER(TRIM(CAST(Rainfall AS STRING)))
                 IN ('true', '1', '1.0')
            THEN 1
            ELSE 0
        END
    ) AS race_rain,

    AVG(
        CASE
            WHEN LOWER(TRIM(CAST(Rainfall AS STRING)))
                 IN ('true', '1', '1.0')
            THEN 1.0
            ELSE 0.0
        END
    ) AS race_rain_fraction

FROM formula1.weather_data

WHERE UPPER(TRIM(CAST(type_of_race AS STRING))) = 'R'

GROUP BY
    CAST(year AS INT),
    CAST(session_number AS INT)
""")

DataFrame[]

In [76]:
spark.sql("""
SELECT
    year,
    COUNT(*) AS race_weather_sessions,
    SUM(race_rain) AS rainy_sessions
FROM race_weather
GROUP BY year
ORDER BY year
""").show()

+----+---------------------+--------------+
|year|race_weather_sessions|rainy_sessions|
+----+---------------------+--------------+
|2020|                   17|             4|
|2021|                   22|             6|
|2022|                   22|             6|
|2023|                   22|             5|
|2024|                   24|             5|
|2025|                   24|             6|
|2026|                    7|             1|
+----+---------------------+--------------+

In [42]:
spark.sql("""
DROP TABLE IF EXISTS formula1.driver_race_modeling
""")

DataFrame[]

In [77]:
modeling_df = spark.sql("""
SELECT
    d.year,
    d.session_number,

    d.driver_number,
    d.driver_id,
    d.team_name,

    q.qualifying_position,
    q.qualifying_field_size,
    q.qualifying_position_percentile,
    q.qualified_top_10,
    q.teammate_qualifying_position,
    q.qualifying_vs_teammate,

    q.valid_qualifying_laps,
    q.best_qualifying_lap,
    q.median_qualifying_lap,
    q.mean_qualifying_lap,
    q.qualifying_lap_sd,
    q.qualifying_gap_to_pole,

    q.maximum_speed_i1,
    q.maximum_speed_i2,
    q.maximum_finish_line_speed,
    q.maximum_speed_trap,

    q.qualifying_stints,
    q.qualifying_compounds,

    q.average_qualifying_position_last_3,
    q.average_qualifying_position_last_5,
    q.average_gap_to_pole_last_5,

    w.race_air_temperature,
    w.race_track_temperature,
    w.race_humidity,
    w.race_pressure,
    w.race_wind_speed,
    w.race_max_wind_speed,
    w.race_min_air_temperature,
    w.race_max_air_temperature,
    w.race_rain,
    w.race_rain_fraction,

    d.previous_finish,
    d.previous_points,
    d.previous_dnf,

    d.average_finish_last_3,
    d.average_finish_last_5,
    d.finish_sd_last_5,

    d.average_points_last_5,
    d.total_points_last_5,
    d.dnf_rate_last_5,
    d.average_positions_gained_last_5,

    d.season_points_before_race,
    d.career_races_before,

    t.team_average_finish_last_3,
    t.team_average_finish_last_5,
    t.team_average_points_last_5,
    t.team_dnf_rate_last_5,

    d.target_position,
    d.target_championship_points

FROM driver_history d

INNER JOIN qualifying_history q
  ON d.year = q.year
 AND d.session_number = q.session_number
 AND d.driver_number = q.driver_number

LEFT JOIN race_weather w
  ON d.year = w.year
 AND d.session_number = w.session_number

LEFT JOIN team_history t
  ON d.year = t.year
 AND d.session_number = t.session_number
 AND d.team_name = t.team_name
""")

In [78]:
(
    modeling_df
    .write
    .mode("overwrite")
    .format("parquet")
    .saveAsTable("formula1.driver_race_modeling")
)

In [44]:
spark.sql("""
SELECT
    year,
    COUNT(*) AS rows,
    COUNT(DISTINCT session_number) AS races
FROM formula1.driver_race_modeling
GROUP BY year
ORDER BY year
""").show()

+----+----+-----+
|year|rows|races|
+----+----+-----+
|2020| 340|   17|
|2021| 438|   22|
|2022| 439|   22|
|2023|  60|    3|
|2025| 478|   24|
|2026| 151|    7|
+----+----+-----+

In [45]:
model_data = spark.table(
    "formula1.driver_race_modeling"
)

model_data.show(5, truncate=False)

+----+--------------+-------------+---------+---------------+-------------------+---------------------+------------------------------+----------------+----------------------------+----------------------+---------------------+-------------------+---------------------+-------------------+------------------+----------------------+----------------+----------------+-------------------------+------------------+-----------------+--------------------+----------------------------------+----------------------------------+--------------------------+--------------------------+----------------------------+-------------------+-------------------+---------------------+---------------+---------------+---------------+------------+---------------------+---------------------+-----------------+---------------------+-------------------+------------------+-------------------------------+-------------------------+-------------------+--------------------------+--------------------------+--------------------------+--------------------+---------------+--------------------------+
|year|session_number|driver_number|driver_id|team_name      |qualifying_position|qualifying_field_size|qualifying_position_percentile|qualified_top_10|teammate_qualifying_position|qualifying_vs_teammate|valid_qualifying_laps|best_qualifying_lap|median_qualifying_lap|mean_qualifying_lap|qualifying_lap_sd |qualifying_gap_to_pole|maximum_speed_i1|maximum_speed_i2|maximum_finish_line_speed|maximum_speed_trap|qualifying_stints|qualifying_compounds|average_qualifying_position_last_3|average_qualifying_position_last_5|average_gap_to_pole_last_5|qualifying_air_temperature|qualifying_track_temperature|qualifying_humidity|qualifying_pressure|qualifying_wind_speed|qualifying_rain|previous_finish|previous_points|previous_dnf|average_finish_last_3|average_finish_last_5|finish_sd_last_5 |average_points_last_5|total_points_last_5|dnf_rate_last_5   |average_positions_gained_last_5|season_points_before_race|career_races_before|team_average_finish_last_3|team_average_finish_last_5|team_average_points_last_5|team_dnf_rate_last_5|target_position|target_championship_points|
+----+--------------+-------------+---------+---------------+-------------------+---------------------+------------------------------+----------------+----------------------------+----------------------+---------------------+-------------------+---------------------+-------------------+------------------+----------------------+----------------+----------------+-------------------------+------------------+-----------------+--------------------+----------------------------------+----------------------------------+--------------------------+--------------------------+----------------------------+-------------------+-------------------+---------------------+---------------+---------------+---------------+------------+---------------------+---------------------+-----------------+---------------------+-------------------+------------------+-------------------------------+-------------------------+-------------------+--------------------------+--------------------------+--------------------------+--------------------+---------------+--------------------------+
|2020|16            |89           |aitken   |Williams       |18                 |20                   |0.894736842105263157894737    |0               |17                          |1                     |6                    |54.892             |55.58                |62.99916666666667  |8.973789509826197 |1.5150000000000006    |290.0           |271.0           |298.0                    |338.0             |3                |1                   |NULL                              |NULL                              |NULL                      |24.014285714285702        |26.928571428571406          |77.40129870129867  |1012.0207792207794 |0.627272727272727    |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL             |NULL                 |NULL               |NULL              |NULL                           |NULL                     |0                  |14.666666666666666        |15.4                      |0.0                       |0.3                 |16             |0.0                       |
|2020|1             |23           |albon    |Red Bull Racing|5                  |20                   |0.210526315789473684210526    |1               |3                           |2                     |12                   |63.746             |64.853               |75.224             |12.106067502027084|0.8070000000000022    |320.0           |255.0           |289.0                    |319.0             |5                |1                   |6.0                               |5.8                               |0.6438000000000045        |24.590666666666667        |49.92666666666667           |34.660000000000004 |940.6559999999994  |1.3826666666666667   |0              |NULL           |NULL           |NULL        |NULL                 |NULL                 |NULL             |NULL                 |NULL               |NULL              |NULL                           |NULL                     |0                  |NULL                      |NULL                      |NULL                      |NULL                |13             |0.0                       |
|2020|2             |23           |albon    |Red Bull Racing|7                  |20                   |0.315789473684210526315789    |1               |2                           |5                     |26                   |79.014             |82.673               |84.02523076923077  |4.295252181725235 |1.188999999999993     |294.0           |216.0           |265.0                    |295.0             |3                |1                   |5.666666666666667                 |5.6                               |0.6478000000000037        |14.839024390243896        |19.911382113821144          |89.77154471544718  |942.5390243902447  |1.3121951219512198   |1              |13             |0.0            |1           |13.0                 |13.0                 |NULL             |0.0                  |0.0                |1.0               |-9.0                           |0.0                      |1                  |16.5                      |16.5                      |0.0                       |1.0                 |4              |12.0                      |
|2020|3             |23           |albon    |Red Bull Racing|13                 |20                   |0.631578947368421052631579    |0               |7                           |6                     |12                   |75.715             |77.115               |88.76341666666667  |13.14084603238961 |2.2680000000000007    |283.0           |256.0           |264.0                    |312.0             |4                |1                   |6.0                               |6.0                               |0.7700000000000017        |18.783116883116875        |27.254545454545454          |71.49870129870133  |987.8467532467536  |1.31038961038961     |0              |4              |12.0           |0           |8.5                  |8.5                  |6.363961030678928|6.0                  |12.0               |0.5               |-3.5                           |12.0                     |2                  |10.0                      |10.0                      |13.5                      |0.5                 |5              |10.0                      |
|2020|4             |23           |albon    |Red Bull Racing|12                 |20                   |0.578947368421052631578947    |0               |3                           |9                     |7                    |86.545             |86.643               |99.05371428571428  |18.167234844762753|2.2420000000000044    |312.0           |267.0           |260.0                    |313.0             |3                |2                   |8.333333333333334                 |7.4                               |1.1198000000000008        |22.497647058823524        |38.937647058823536          |54.387058823529415 |997.7188235294107  |3.967058823529413    |0              |5              |10.0           |0           |7.333333333333333    |7.333333333333333    |4.932882862316247|7.333333333333333    |22.0               |0.3333333333333333|0.3333333333333333             |22.0                     |3                  |7.833333333333333         |7.833333333333333         |18.333333333333332        |0.3333333333333333  |8              |4.0                       |
+----+--------------+-------------+---------+---------------+-------------------+---------------------+------------------------------+----------------+----------------------------+----------------------+---------------------+-------------------+---------------------+-------------------+------------------+----------------------+----------------+----------------+-------------------------+------------------+-----------------+--------------------+----------------------------------+----------------------------------+--------------------------+--------------------------+----------------------------+-------------------+-------------------+---------------------+---------------+---------------+---------------+------------+---------------------+---------------------+-----------------+---------------------+-------------------+------------------+-------------------------------+-------------------------+-------------------+--------------------------+--------------------------+--------------------------+--------------------+---------------+--------------------------+
only showing top 5 rows

In [46]:
train_data = model_data.filter(
    F.col("year") <= 2023
)

validation_data = model_data.filter(
    F.col("year") == 2024
)

test_data = model_data.filter(
    F.col("year") >= 2025
)

print("Training rows:", train_data.count())
print("Validation rows:", validation_data.count())
print("Test rows:", test_data.count())

Training rows: 1277
Validation rows: 0
Test rows: 629

In [58]:
from pyspark.sql import functions as F

from pyspark.ml import Pipeline
from pyspark.ml.feature import (
    Imputer,
    StringIndexer,
    OneHotEncoder,
    VectorAssembler
)
from pyspark.ml.regression import LinearRegression
from pyspark.ml.evaluation import RegressionEvaluator

In [59]:
model_data = (
    spark.table("formula1.driver_race_modeling")
    .filter(F.col("target_position").isNotNull())
)

LABEL = "target_position"

print("Rows:", model_data.count())

Rows: 1906

In [60]:
available_years = [
    row["year"]
    for row in (
        model_data
        .select("year")
        .distinct()
        .orderBy("year")
        .collect()
    )
]

if len(available_years) < 3:
    raise ValueError(
        "At least three seasons are needed for "
        "training, validation, and testing."
    )

VALIDATION_YEAR = available_years[-2]
TEST_YEAR = available_years[-1]

train_data = (
    model_data
    .filter(F.col("year") < VALIDATION_YEAR)
    .cache()
)

validation_data = (
    model_data
    .filter(F.col("year") == VALIDATION_YEAR)
    .cache()
)

test_data = (
    model_data
    .filter(F.col("year") == TEST_YEAR)
    .cache()
)

print("Available years:", available_years)
print("Validation year:", VALIDATION_YEAR)
print("Test year:", TEST_YEAR)

print("Training rows:", train_data.count())
print("Validation rows:", validation_data.count())
print("Test rows:", test_data.count())

Available years: [2020, 2021, 2022, 2023, 2025, 2026]
Validation year: 2025
Test year: 2026
Training rows: 1277
Validation rows: 478
Test rows: 151

In [47]:
LABEL = "target_position"

In [48]:
LABEL = "target_championship_points"

In [79]:
requested_numeric_features = [
    "session_number",

    # Current qualifying result
    "qualifying_position",
    "qualifying_field_size",
    "qualifying_position_percentile",
    "qualified_top_10",
    "teammate_qualifying_position",
    "qualifying_vs_teammate",

    # Current qualifying performance
    "valid_qualifying_laps",
    "best_qualifying_lap",
    "median_qualifying_lap",
    "mean_qualifying_lap",
    "qualifying_lap_sd",
    "qualifying_gap_to_pole",

    # Qualifying speed
    "maximum_speed_i1",
    "maximum_speed_i2",
    "maximum_finish_line_speed",
    "maximum_speed_trap",

    # Qualifying session usage
    "qualifying_stints",
    "qualifying_compounds",

    # Historical qualifying form
    "average_qualifying_position_last_3",
    "average_qualifying_position_last_5",
    "average_gap_to_pole_last_5",

    # Actual race weather
    "race_air_temperature",
    "race_track_temperature",
    "race_humidity",
    "race_pressure",
    "race_wind_speed",
    "race_max_wind_speed",
    "race_min_air_temperature",
    "race_max_air_temperature",
    "race_rain",
    "race_rain_fraction",

    # Previous race
    "previous_finish",
    "previous_points",
    "previous_dnf",

    # Historical driver form
    "average_finish_last_3",
    "average_finish_last_5",
    "finish_sd_last_5",
    "average_points_last_5",
    "total_points_last_5",
    "dnf_rate_last_5",
    "average_positions_gained_last_5",

    # Season and career
    "season_points_before_race",
    "career_races_before",

    # Historical team performance
    "team_average_finish_last_3",
    "team_average_finish_last_5",
    "team_average_points_last_5",
    "team_dnf_rate_last_5"
]

categorical_features = [
    "driver_id",
    "team_name"
]

In [80]:
numeric_features = [
    column
    for column in requested_numeric_features
    if column in model_data.columns
]

categorical_features = [
    column
    for column in categorical_features
    if column in model_data.columns
]

missing_features = sorted(
    set(requested_numeric_features)
    - set(numeric_features)
)

print("Numeric features:", len(numeric_features))
print("Categorical features:", categorical_features)
print("Missing optional features:", missing_features)

Numeric features: 38
Categorical features: ['driver_id', 'team_name']
Missing optional features: ['race_air_temperature', 'race_humidity', 'race_max_air_temperature', 'race_max_wind_speed', 'race_min_air_temperature', 'race_pressure', 'race_rain', 'race_rain_fraction', 'race_track_temperature', 'race_wind_speed']

In [81]:
for column in numeric_features:
    model_data = model_data.withColumn(
        column,
        F.col(column).cast("double")
    )

In [82]:
def create_regression_pipeline(
    label_col,
    reg_param,
    elastic_net_param
):
    imputed_columns = [
        f"{column}_imputed"
        for column in numeric_features
    ]

    imputer = Imputer(
        inputCols=numeric_features,
        outputCols=imputed_columns,
        strategy="median"
    )

    indexers = [
        StringIndexer(
            inputCol=column,
            outputCol=f"{column}_index",
            handleInvalid="keep"
        )
        for column in categorical_features
    ]

    encoder = OneHotEncoder(
        inputCols=[
            f"{column}_index"
            for column in categorical_features
        ],
        outputCols=[
            f"{column}_ohe"
            for column in categorical_features
        ],
        handleInvalid="keep",
        dropLast=True
    )

    assembler_inputs = (
        imputed_columns
        + [
            f"{column}_ohe"
            for column in categorical_features
        ]
    )

    assembler = VectorAssembler(
        inputCols=assembler_inputs,
        outputCol="features",
        handleInvalid="keep"
    )

    regression = LinearRegression(
        featuresCol="features",
        labelCol=label_col,
        predictionCol="prediction",

        regParam=reg_param,
        elasticNetParam=elastic_net_param,

        fitIntercept=True,
        standardization=True,
        solver="auto",
        maxIter=1000,
        tol=1e-6
    )

    return Pipeline(
        stages=[
            imputer,
            *indexers,
            encoder,
            assembler,
            regression
        ]
    )

In [83]:
def regression_metrics(
    fitted_pipeline,
    data,
    label_col
):
    predictions = fitted_pipeline.transform(data)

    metric_values = {}

    for metric_name in ["rmse", "mae", "r2"]:
        evaluator = RegressionEvaluator(
            labelCol=label_col,
            predictionCol="prediction",
            metricName=metric_name
        )

        metric_values[metric_name] = evaluator.evaluate(
            predictions
        )

    return metric_values, predictions

In [84]:
model_candidates = [
    {
        "model": "Linear regression",
        "reg_param": 0.0,
        "elastic_net": 0.0
    },

    {
        "model": "Ridge",
        "reg_param": 0.0001,
        "elastic_net": 0.0
    },
    {
        "model": "Ridge",
        "reg_param": 0.001,
        "elastic_net": 0.0
    },
    {
        "model": "Ridge",
        "reg_param": 0.01,
        "elastic_net": 0.0
    },
    {
        "model": "Ridge",
        "reg_param": 0.1,
        "elastic_net": 0.0
    },
    {
        "model": "Ridge",
        "reg_param": 1.0,
        "elastic_net": 0.0
    },
    {
        "model": "Ridge",
        "reg_param": 10.0,
        "elastic_net": 0.0
    },

    {
        "model": "Lasso",
        "reg_param": 0.0001,
        "elastic_net": 1.0
    },
    {
        "model": "Lasso",
        "reg_param": 0.001,
        "elastic_net": 1.0
    },
    {
        "model": "Lasso",
        "reg_param": 0.01,
        "elastic_net": 1.0
    },
    {
        "model": "Lasso",
        "reg_param": 0.1,
        "elastic_net": 1.0
    },
    {
        "model": "Lasso",
        "reg_param": 1.0,
        "elastic_net": 1.0
    },
    {
        "model": "Lasso",
        "reg_param": 10.0,
        "elastic_net": 1.0
    }
]

In [139]:
validation_results = []
candidate_models = {}

for candidate in model_candidates:
    model_name = candidate["model"]
    reg_param = candidate["reg_param"]
    elastic_net = candidate["elastic_net"]

    pipeline = create_regression_pipeline(
        label_col=LABEL,
        reg_param=reg_param,
        elastic_net_param=elastic_net
    )

    fitted_pipeline = pipeline.fit(train_data)

    metrics, _ = regression_metrics(
        fitted_pipeline,
        validation_data,
        LABEL
    )

    model_key = (
        model_name,
        reg_param,
        elastic_net
    )

    candidate_models[model_key] = fitted_pipeline

    validation_results.append({
        "model": model_name,
        "reg_param": float(reg_param),
        "elastic_net": float(elastic_net),
        "validation_rmse": float(metrics["rmse"]),
        "validation_mae": float(metrics["mae"]),
        "validation_r2": float(metrics["r2"])
    })

26/07/11 01:33:07 WARN Instrumentation: [81abeb89] regParam is zero, which might cause numerical instability and overfitting.
26/07/11 01:33:07 WARN Instrumentation: [81abeb89] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.

In [140]:
validation_results_df = (
    spark.createDataFrame(validation_results)
    .orderBy("validation_rmse")
)

validation_results_df.show(
    100,
    truncate=False
)

+-----------+-----------------+---------+------------------+----------------------+------------------+
|elastic_net|model            |reg_param|validation_mae    |validation_r2         |validation_rmse   |
+-----------+-----------------+---------+------------------+----------------------+------------------+
|1.0        |Lasso            |0.1      |3.558193037916339 |0.4039261213682659    |4.435803737890841 |
|0.0        |Ridge            |10.0     |3.555335982131466 |0.3987704902443876    |4.454945768973974 |
|1.0        |Lasso            |1.0      |3.688120339707216 |0.38993857275091925   |4.487547520641759 |
|0.0        |Ridge            |1.0      |3.536289492024605 |0.3875163092457752    |4.496447652291112 |
|1.0        |Lasso            |0.01     |3.647843890304489 |0.3544123035237078    |4.616362450978999 |
|0.0        |Ridge            |0.1      |3.6528414014617994|0.3494304827913124    |4.6341398138175665|
|0.0        |Ridge            |0.01     |3.6977922678984294|0.32833950777496734   |4.708658338085966 |
|1.0        |Lasso            |0.001    |3.696751320574999 |0.3262315041173921    |4.7160416018305495|
|0.0        |Ridge            |0.001    |3.7068271605475944|0.3229849505408616    |4.727390071114966 |
|0.0        |Ridge            |1.0E-4   |3.708606987130997 |0.32239457182172726   |4.729450839419117 |
|1.0        |Lasso            |1.0E-4   |3.709622229220164 |0.3221250208127654    |4.730391432156672 |
|0.0        |Linear regression|0.0      |3.7166519331095014|0.3210766869092081    |4.734047795102213 |
|1.0        |Lasso            |10.0     |4.981084720661344 |-1.0932872187563447E-5|5.745457961739316 |
+-----------+-----------------+---------+------------------+----------------------+------------------+

In [141]:
best_models = {}

for model_family in [
    "Linear regression",
    "Ridge",
    "Lasso"
]:
    family_results = [
        result
        for result in validation_results
        if result["model"] == model_family
    ]

    best_models[model_family] = min(
        family_results,
        key=lambda row: row["validation_rmse"]
    )

best_models

{'Linear regression': {'model': 'Linear regression',
  'reg_param': 0.0,
  'elastic_net': 0.0,
  'validation_rmse': 4.734047795102213,
  'validation_mae': 3.7166519331095014,
  'validation_r2': 0.3210766869092081},
 'Ridge': {'model': 'Ridge',
  'reg_param': 10.0,
  'elastic_net': 0.0,
  'validation_rmse': 4.454945768973974,
  'validation_mae': 3.555335982131466,
  'validation_r2': 0.3987704902443876},
 'Lasso': {'model': 'Lasso',
  'reg_param': 0.1,
  'elastic_net': 1.0,
  'validation_rmse': 4.435803737890841,
  'validation_mae': 3.558193037916339,
  'validation_r2': 0.4039261213682659}}

In [142]:
best_models_df = spark.createDataFrame(
    list(best_models.values())
)

best_models_df.orderBy(
    "validation_rmse"
).show(truncate=False)

+-----------+-----------------+---------+------------------+------------------+-----------------+
|elastic_net|model            |reg_param|validation_mae    |validation_r2     |validation_rmse  |
+-----------+-----------------+---------+------------------+------------------+-----------------+
|1.0        |Lasso            |0.1      |3.558193037916339 |0.4039261213682659|4.435803737890841|
|0.0        |Ridge            |10.0     |3.555335982131466 |0.3987704902443876|4.454945768973974|
|0.0        |Linear regression|0.0      |3.7166519331095014|0.3210766869092081|4.734047795102213|
+-----------+-----------------+---------+------------------+------------------+-----------------+

In [143]:
train_validation_data = train_data.unionByName(
    validation_data
)

final_models = {}
test_results = []
test_prediction_sets = {}

for model_family, specification in best_models.items():
    final_pipeline = create_regression_pipeline(
        label_col=LABEL,
        reg_param=specification["reg_param"],
        elastic_net_param=specification["elastic_net"]
    )

    fitted_final_model = final_pipeline.fit(
        train_validation_data
    )

    metrics, predictions = regression_metrics(
        fitted_final_model,
        test_data,
        LABEL
    )

    final_models[model_family] = fitted_final_model
    test_prediction_sets[model_family] = predictions

    test_results.append({
        "model": model_family,
        "reg_param": float(
            specification["reg_param"]
        ),
        "elastic_net": float(
            specification["elastic_net"]
        ),
        "test_rmse": float(metrics["rmse"]),
        "test_mae": float(metrics["mae"]),
        "test_r2": float(metrics["r2"])
    })

26/07/11 01:33:19 WARN Instrumentation: [b966997d] regParam is zero, which might cause numerical instability and overfitting.
26/07/11 01:33:19 WARN Instrumentation: [b966997d] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.

In [144]:
import pandas as pd
import numpy as np

lasso_pipeline_model = final_models["Lasso"]

# Final stage is the fitted LinearRegression model
lasso_model = lasso_pipeline_model.stages[-1]

# Transform one row so Spark creates feature-vector metadata
transformed_sample = lasso_pipeline_model.transform(
    train_validation_data.limit(1)
)

feature_metadata = (
    transformed_sample
    .schema["features"]
    .metadata["ml_attr"]["attrs"]
)

feature_attributes = []

for attribute_type in ["numeric", "binary", "nominal"]:
    feature_attributes.extend(
        feature_metadata.get(attribute_type, [])
    )

feature_attributes = sorted(
    feature_attributes,
    key=lambda attribute: attribute["idx"]
)

feature_names = [
    attribute["name"]
    for attribute in feature_attributes
]

coefficients = lasso_model.coefficients.toArray()

lasso_coefficients = pd.DataFrame({
    "predictor": feature_names,
    "coefficient": coefficients
})

lasso_coefficients["absolute_coefficient"] = (
    lasso_coefficients["coefficient"].abs()
)

In [145]:
SELECTED_TOLERANCE = 1e-8

selected_predictors = (
    lasso_coefficients
    .loc[
        lasso_coefficients["absolute_coefficient"]
        > SELECTED_TOLERANCE
    ]
    .sort_values(
        "absolute_coefficient",
        ascending=False
    )
    .reset_index(drop=True)
)

selected_predictors

,predictor,coefficient,absolute_coefficient
0,qualifying_position_percentile_imputed,3.677992,3.677992
1,team_name_ohe_Racing Bulls,0.677258,0.677258
2,team_name_ohe_Mercedes,-0.555903,0.555903
3,team_name_ohe_Red Bull Racing,-0.419789,0.419789
4,team_name_ohe_Williams,0.348159,0.348159
5,team_name_ohe_Haas F1 Team,0.329715,0.329715
6,team_name_ohe_Alfa Romeo,0.288563,0.288563
7,team_name_ohe_AlphaTauri,0.215151,0.215151
8,qualifying_position_imputed,0.208060,0.208060
9,team_name_ohe_McLaren,-0.133078,0.133078
10,team_average_finish_last_5_imputed,0.118342,0.118342
11,average_positions_gained_last_5_imputed,0.096204,0.096204
12,team_name_ohe_Alpine,0.065617,0.065617
13,average_qualifying_position_last_5_imputed,0.057639,0.057639
14,previous_finish_imputed,0.038213,0.038213
15,team_average_finish_last_3_imputed,0.027976,0.027976
16,average_finish_last_3_imputed,0.015174,0.015174
17,qualifying_gap_to_pole_imputed,-0.010894,0.010894
18,average_points_last_5_imputed,-0.007312,0.007312
19,session_number_imputed,0.005561,0.005561
20,valid_qualifying_laps_imputed,0.004339,0.004339
21,season_points_before_race_imputed,-0.004031,0.004031
22,career_races_before_imputed,-0.001989,0.001989
23,teammate_qualifying_position_imputed,0.001216,0.001216

In [92]:
from pyspark.sql import functions as F

base_modeling_df = spark.table(
    "formula1.driver_race_modeling"
)

print("Rows:", base_modeling_df.count())
print("Years:")

base_modeling_df.select("year").distinct().orderBy("year").show()

Rows: 1906
Years:
+----+
|year|
+----+
|2020|
|2021|
|2022|
|2023|
|2025|
|2026|
+----+

In [94]:
results = spark.table("formula1.results")

results_columns = set(results.columns)

if "FullName" in results_columns:
    driver_name_expression = F.col("FullName")

elif {"FirstName", "LastName"}.issubset(results_columns):
    driver_name_expression = F.concat_ws(
        " ",
        F.col("FirstName"),
        F.col("LastName")
    )

elif "BroadcastName" in results_columns:
    driver_name_expression = F.col("BroadcastName")

else:
    raise ValueError(
        "No usable driver-name column was found."
    )

driver_name_lookup = (
    results
    .filter(
        F.upper(
            F.trim(F.col("type_of_race"))
        ) == "R"
    )
    .select(
        F.col("year").cast("int").alias("year"),

        F.col("session_number")
        .cast("int")
        .alias("session_number"),

        F.col("DriverNumber")
        .cast("string")
        .alias("driver_number"),

        F.trim(
            driver_name_expression
        ).alias("driver_name")
    )
    .filter(F.col("driver_name").isNotNull())
    .dropDuplicates(
        [
            "year",
            "session_number",
            "driver_number"
        ]
    )
)

In [122]:
ratings_text = """
Driver	Rating	Year
Lewis Hamilton	94	22
Verstappen	94	22
Charles Leclerc	92	22
George Russell	90	22
Lando Norris	90	22
Fernando Alonso	89	22
Sergio Perez	88	22
Valtteri Bottas	88	22
Carlos Sainz	87	22
Sebastian Vettel	85	22
Pierre Gasly	84	22
Esteban Ocon	83	22
Daniel Ricciardo	83	22
Alex Albon	82	22
Kevin Magnussen	81	22
Lance Stroll	80	22
Yuki Tsuonda	78	22
Mick Schumacher	77	22
Zhou Guanyu	70	22
Nicholas Latifi	70	22
Lewis Hamilton	94	21
Valtteri Bottas	90	21
Max Verstappen	93	21
Sergio Perez	86	21
Charles Leclerc	89	21
Carlos Sainz Jr.	89	21
Sebastian Vettel	89	21
Lance Stroll	82	21
Daniel Ricciardo	89	21
Lando Norris	89	21
Fernando Alonso	89	21
Esteban Ocon	83	21
Pierre Gasly	89	21
Yuki Tsunoda	77	21
Kimi Raikkonen	87	21
Antonio Giovinazzi	81	21
Mick Schumacher	80	21
Nikita Mazepin	67	21
George Russell	81	21
Nicholas Latifi	72	21
Lewis Hamilton	94	20
Valtteri Bottas	90	20
Max Verstappen	90	20
Charles Leclerc	86	20
Sebastian Vettel	89	20
Carlos Sainz Jr.	82	20
Pierre Gasly	80	20
Alexander Albon	79	20
Daniel Ricciardo	87	20
Sergio Perez	85	20
Lando Norris	79	20
Kimi Raikkonen	87	20
Daniil Kvyat	80	20
Lance Stroll	78	20
Kevin Magnussen	78	20
Antonio Giovinazzi	73	20
Romain Grosjean	80	20
George Russell	75	20
Esteban Ocon	80	20
Nicholas Latifi	64	20
Max Verstappen	95	26
Lewis Hamilton	92	26
George Russell	92	26
Charles Leclerc	92	26
Lando Norris	92	26
Oscar Piastri	91	26
Fernando Alonso	89	26
Kimi Antonelli	88	26
Pierre Gasly	85	26
Carlos Sainz	85	26
Nico Hülkenberg	85	26
Sergio Perez	85	26
Isack Hadjar	84	26
Esteban Ocon	84	26
Oliver Bearman	83	26
Alexander Albon	83	26
Valtteri Bottas	82	26
Gabriel Bortoleto	81	26
Liam Lawson	80	26
Lance Stroll	77	26
Franco Colapinto	73	26
Arvid Lindblad	73	26
Max Verstappen	96	24
Fernando Alonso	92	24
Carlos Sainz	89	24
Charles Leclerc	89	24
Lando Norris	89	24
Lewis Hamilton	89	24
George Russell	87	24
Sergio Perez	87	24
Alex Albon	85	24
Oscar Piastri	84	24
Pierre Gasly	84	24
Esteban Ocon	83	24
Daniel Ricciardo	82	24
Nico Hulkenberg	82	24
Valtteri Bottas	81	24
Yuki Tsunoda	81	24
Kevin Magnussen	80	24
Lance Stroll	80	24
Zhou Guanyu	80	24
Logan Sargeant	70	24
Max Verstappen	96	23
Lewis Hamilton	92	23
Fernando Alonso	92	23
Charles Leclerc	90	23
Carlos Sainz Jr.	90	23
Sergio Perez	87	23
George Russell	87	23
Lando Norris	89	23
Valtteri Bottas	87	23
Esteban Ocon	86	23
Pierre Gasly	85	23
Oscar Piastri	85	23
Lance Stroll	84	23
Alexander Albon	83	23
Yuki Tsunoda	83	23
Kevin Magnussen	81	23
Nico Hulkenberg	80	23
Zhou Guanyu	78	23
Logan Sargeant	71	23
Nyck de Vries	71	23
Max Verstappen	95	25
Lando Norris	92	25
Charles Leclerc	92	25
George Russell	92	25
Oscar Piastri	91	25
Lewis Hamilton	91	25
Fernando Alonso	89	25
Nico Hülkenberg	86	25
Alexander Albon	85	25
Pierre Gasly	85	25
Carlos Sainz	85	25
Esteban Ocon	83	25
Isack Hadjar	82	25
Kimi Antonelli	80	25
Oliver Bearman	80	25
Gabriel Bortoleto	79	25
Yuki Tsunoda	77	25
Liam Lawson	77	25
Lance Stroll	77	25
Franco Colapinto	73	25
"""

In [123]:
import pandas as pd
from io import StringIO

ratings_pd = pd.read_csv(
    StringIO(ratings_text.strip()),
    sep="\t"
)

ratings_pd = ratings_pd.rename(
    columns={
        "Driver": "rating_driver_name",
        "Rating": "driver_rating",
        "Year": "year"
    }
)

ratings_pd["year"] = ratings_pd["year"].astype(int)

ratings_pd["year"] = ratings_pd["year"].apply(
    lambda year: year + 2000
    if year < 100
    else year
)

ratings_pd["driver_rating"] = (
    ratings_pd["driver_rating"]
    .astype(float)
)

ratings_pd.head()

  rating_driver_name  driver_rating  year
0     Lewis Hamilton           94.0  2022
1         Verstappen           94.0  2022
2    Charles Leclerc           92.0  2022
3     George Russell           90.0  2022
4       Lando Norris           90.0  2022

In [124]:
import re
import unicodedata

name_aliases = {
    "verstappen": "max verstappen",

    "alex albon": "alexander albon",

    "carlos sainz jr": "carlos sainz",

    "zhou guanyu": "guanyu zhou",

    "yuki tsuonda": "yuki tsunoda",

    "kimi antonelli": "andrea kimi antonelli",

    "nico hulkenberg": "nico hulkenberg",
    "kimi raikkonen": "kimi raikkonen"
}


def normalize_driver_name(name):
    if name is None:
        return None

    normalized = unicodedata.normalize(
        "NFKD",
        str(name)
    )

    normalized = "".join(
        character
        for character in normalized
        if not unicodedata.combining(character)
    )

    normalized = normalized.lower()

    normalized = re.sub(
        r"[^a-z0-9 ]",
        " ",
        normalized
    )

    normalized = re.sub(
        r"\s+",
        " ",
        normalized
    ).strip()

    return name_aliases.get(
        normalized,
        normalized
    )

In [125]:
ratings_pd["normalized_driver_name"] = (
    ratings_pd["rating_driver_name"]
    .apply(normalize_driver_name)
)

ratings_pd[
    [
        "year",
        "rating_driver_name",
        "normalized_driver_name",
        "driver_rating"
    ]
].head(30)

ratings_spark = spark.createDataFrame(
    ratings_pd[
        [
            "year",
            "rating_driver_name",
            "normalized_driver_name",
            "driver_rating"
        ]
    ]
)

ratings_spark.show(30, truncate=False)

+----+------------------+----------------------+-------------+
|year|rating_driver_name|normalized_driver_name|driver_rating|
+----+------------------+----------------------+-------------+
|2022|Lewis Hamilton    |lewis hamilton        |94.0         |
|2022|Verstappen        |max verstappen        |94.0         |
|2022|Charles Leclerc   |charles leclerc       |92.0         |
|2022|George Russell    |george russell        |90.0         |
|2022|Lando Norris      |lando norris          |90.0         |
|2022|Fernando Alonso   |fernando alonso       |89.0         |
|2022|Sergio Perez      |sergio perez          |88.0         |
|2022|Valtteri Bottas   |valtteri bottas       |88.0         |
|2022|Carlos Sainz      |carlos sainz          |87.0         |
|2022|Sebastian Vettel  |sebastian vettel      |85.0         |
|2022|Pierre Gasly      |pierre gasly          |84.0         |
|2022|Esteban Ocon      |esteban ocon          |83.0         |
|2022|Daniel Ricciardo  |daniel ricciardo      |83.0         |
|2022|Alex Albon        |alexander albon       |82.0         |
|2022|Kevin Magnussen   |kevin magnussen       |81.0         |
|2022|Lance Stroll      |lance stroll          |80.0         |
|2022|Yuki Tsuonda      |yuki tsunoda          |78.0         |
|2022|Mick Schumacher   |mick schumacher       |77.0         |
|2022|Zhou Guanyu       |guanyu zhou           |70.0         |
|2022|Nicholas Latifi   |nicholas latifi       |70.0         |
|2021|Lewis Hamilton    |lewis hamilton        |94.0         |
|2021|Valtteri Bottas   |valtteri bottas       |90.0         |
|2021|Max Verstappen    |max verstappen        |93.0         |
|2021|Sergio Perez      |sergio perez          |86.0         |
|2021|Charles Leclerc   |charles leclerc       |89.0         |
|2021|Carlos Sainz Jr.  |carlos sainz          |89.0         |
|2021|Sebastian Vettel  |sebastian vettel      |89.0         |
|2021|Lance Stroll      |lance stroll          |82.0         |
|2021|Daniel Ricciardo  |daniel ricciardo      |89.0         |
|2021|Lando Norris      |lando norris          |89.0         |
+----+------------------+----------------------+-------------+
only showing top 30 rows

In [126]:
from pyspark.sql.types import StringType
from pyspark.sql.functions import udf

normalize_driver_name_udf = udf(
    normalize_driver_name,
    StringType()
)

driver_name_lookup = (
    driver_name_lookup
    .withColumn(
        "normalized_driver_name",
        normalize_driver_name_udf(
            "driver_name"
        )
    )
)

In [127]:
modeling_with_names = (
    base_modeling_df
    .join(
        driver_name_lookup,
        on=[
            "year",
            "session_number",
            "driver_number"
        ],
        how="left"
    )
)

In [128]:
modeling_with_ratings_check = (
    modeling_with_names
    .join(
        ratings_spark.select(
            "year",
            "normalized_driver_name",
            "driver_rating"
        ),
        on=[
            "year",
            "normalized_driver_name"
        ],
        how="left"
    )
)

In [129]:
unmatched_ratings = (
    modeling_with_ratings_check
    .filter(
        (F.col("year") >= 2020)
        & F.col("driver_rating").isNull()
    )
    .select(
        "year",
        "driver_name",
        "normalized_driver_name"
    )
    .distinct()
    .orderBy(
        "year",
        "driver_name"
    )
)

unmatched_ratings.show(
    100,
    truncate=False
)

+----+-----------------+----------------------+
|year|driver_name      |normalized_driver_name|
+----+-----------------+----------------------+
|2020|Jack Aitken      |jack aitken           |
|2020|Nico Hulkenberg  |nico hulkenberg       |
|2020|Pietro Fittipaldi|pietro fittipaldi     |
|2021|Robert Kubica    |robert kubica         |
|2022|Nico Hulkenberg  |nico hulkenberg       |
|2022|Nyck De Vries    |nyck de vries         |
|2025|Jack Doohan      |jack doohan           |
+----+-----------------+----------------------+

In [130]:
ratings_spark.groupBy(
    "year",
    "normalized_driver_name"
).count().filter(
    F.col("count") > 1
).show(truncate=False)

+----+----------------------+-----+
|year|normalized_driver_name|count|
+----+----------------------+-----+
+----+----------------------+-----+

In [131]:
driver_rating_modeling_df = (
    modeling_with_ratings_check
    .filter(
        F.col("driver_rating").isNotNull()
    )
)

In [132]:
driver_rating_modeling_df = (
    modeling_with_ratings_check
    .filter(
        F.col("driver_rating").isNotNull()
    )
)

In [133]:
driver_rating_modeling_df.groupBy(
    "year"
).agg(
    F.count("*").alias("rows"),
    F.countDistinct("driver_name").alias(
        "drivers"
    ),
    F.min("driver_rating").alias(
        "minimum_rating"
    ),
    F.max("driver_rating").alias(
        "maximum_rating"
    )
).orderBy("year").show()

+----+----+-------+--------------+--------------+
|year|rows|drivers|minimum_rating|maximum_rating|
+----+----+-------+--------------+--------------+
|2020| 334|     20|          64.0|          94.0|
|2021| 436|     20|          67.0|          94.0|
|2022| 436|     20|          70.0|          94.0|
|2023|  60|     20|          71.0|          96.0|
|2025| 472|     21|          73.0|          95.0|
|2026| 151|     22|          73.0|          95.0|
+----+----+-------+--------------+--------------+

In [135]:
spark.sql("""
DROP TABLE IF EXISTS
formula1.driver_race_modeling_with_ratings
""")

DataFrame[]

In [136]:
(
    driver_rating_modeling_df
    .write
    .mode("overwrite")
    .format("parquet")
    .saveAsTable(
        "formula1.driver_race_modeling_with_ratings"
    )
)

In [113]:
requested_numeric_features = [
    "session_number",
    "driver_rating",

    "qualifying_position",
    "qualifying_field_size",
    "qualifying_position_percentile",
    "qualified_top_10",
    "teammate_qualifying_position",
    "qualifying_vs_teammate",

    "valid_qualifying_laps",
    "best_qualifying_lap",
    "median_qualifying_lap",
    "mean_qualifying_lap",
    "qualifying_lap_sd",
    "qualifying_gap_to_pole",

    "maximum_speed_i1",
    "maximum_speed_i2",
    "maximum_finish_line_speed",
    "maximum_speed_trap",

    "qualifying_stints",
    "qualifying_compounds",

    "average_qualifying_position_last_3",
    "average_qualifying_position_last_5",
    "average_gap_to_pole_last_5",

    "race_air_temperature",
    "race_track_temperature",
    "race_humidity",
    "race_pressure",
    "race_wind_speed",
    "race_rain",
    "race_rain_fraction",

    "previous_finish",
    "previous_points",
    "previous_dnf",

    "average_finish_last_3",
    "average_finish_last_5",
    "finish_sd_last_5",

    "average_points_last_5",
    "total_points_last_5",
    "dnf_rate_last_5",
    "average_positions_gained_last_5",

    "season_points_before_race",
    "career_races_before",

    "team_average_finish_last_3",
    "team_average_finish_last_5",
    "team_average_points_last_5",
    "team_dnf_rate_last_5"
]

In [137]:
categorical_features = [
    "team_name"
]

In [138]:
identifier_columns = [
    "year",
    "session_number",
    "driver_number",
    "driver_id",
    "driver_name",
    "normalized_driver_name"
]

In [146]:
# ============================================================
# FORMULA 1: LINEAR REGRESSION, RIDGE, AND LASSO PIPELINE
# ============================================================

from pyspark.sql import functions as F
from pyspark.ml import Pipeline
from pyspark.ml.feature import (
    Imputer,
    StringIndexer,
    OneHotEncoder,
    VectorAssembler
)
from pyspark.ml.regression import LinearRegression
from pyspark.ml.evaluation import RegressionEvaluator

import pandas as pd
import numpy as np


# ------------------------------------------------------------
# 1. CONFIGURATION
# ------------------------------------------------------------

SOURCE_TABLE = "formula1.driver_race_modeling_with_ratings"
LABEL = "target_position"

# Preferred chronological split.
# Change these if you want to test different seasons.
PREFERRED_VALIDATION_YEAR = 2024
PREFERRED_TEST_YEAR = 2025

# Ridge and lasso penalty values to test.
REGULARIZATION_GRID = [
    0.0001,
    0.001,
    0.01,
    0.1,
    1.0,
    10.0
]

# Coefficients smaller than this are treated as zero.
LASSO_SELECTION_TOLERANCE = 1e-8


# ------------------------------------------------------------
# 2. LOAD THE NEW MODELING DATASET
# ------------------------------------------------------------

model_data = (
    spark.table(SOURCE_TABLE)
    .filter(F.col(LABEL).isNotNull())
)

print("Source table:", SOURCE_TABLE)
print("Total rows:", model_data.count())
print("Total columns:", len(model_data.columns))


# ------------------------------------------------------------
# 3. DEFINE REQUESTED PREDICTORS
# ------------------------------------------------------------

requested_numeric_features = [
    "session_number",

    # Numeric replacement for driver identity
    "driver_rating",

    # Current qualifying results
    "qualifying_position",
    "qualifying_field_size",
    "qualifying_position_percentile",
    "qualified_top_10",
    "teammate_qualifying_position",
    "qualifying_vs_teammate",

    # Current qualifying lap performance
    "valid_qualifying_laps",
    "best_qualifying_lap",
    "median_qualifying_lap",
    "mean_qualifying_lap",
    "qualifying_lap_sd",
    "qualifying_gap_to_pole",

    # Qualifying speed
    "maximum_speed_i1",
    "maximum_speed_i2",
    "maximum_finish_line_speed",
    "maximum_speed_trap",

    # Qualifying session usage
    "qualifying_stints",
    "qualifying_compounds",

    # Historical qualifying form
    "average_qualifying_position_last_3",
    "average_qualifying_position_last_5",
    "average_gap_to_pole_last_5",

    # Actual race weather
    "race_air_temperature",
    "race_track_temperature",
    "race_humidity",
    "race_pressure",
    "race_wind_speed",
    "race_max_wind_speed",
    "race_min_air_temperature",
    "race_max_air_temperature",
    "race_rain",
    "race_rain_fraction",

    # Previous race
    "previous_finish",
    "previous_points",
    "previous_dnf",

    # Historical driver form
    "average_finish_last_3",
    "average_finish_last_5",
    "finish_sd_last_5",
    "average_points_last_5",
    "total_points_last_5",
    "dnf_rate_last_5",
    "average_positions_gained_last_5",

    # Season and career
    "season_points_before_race",
    "career_races_before",

    # Historical constructor form
    "team_average_finish_last_3",
    "team_average_finish_last_5",
    "team_average_points_last_5",
    "team_dnf_rate_last_5"
]

# Driver identity is intentionally excluded.
requested_categorical_features = [
    "team_name"
]

identifier_columns = [
    "year",
    "session_number",
    "driver_number",
    "driver_id",
    "driver_name",
    "normalized_driver_name",
    "team_name"
]


# ------------------------------------------------------------
# 4. KEEP ONLY COLUMNS THAT EXIST
# ------------------------------------------------------------

numeric_features = [
    column
    for column in requested_numeric_features
    if column in model_data.columns
]

categorical_features = [
    column
    for column in requested_categorical_features
    if column in model_data.columns
]

missing_numeric_features = sorted(
    set(requested_numeric_features)
    - set(numeric_features)
)

print("\nNumeric features found:", len(numeric_features))
print("Categorical features found:", categorical_features)

if missing_numeric_features:
    print("\nMissing optional numeric features:")
    for column in missing_numeric_features:
        print(" -", column)


# ------------------------------------------------------------
# 5. CAST NUMERIC FEATURES AND LABEL TO DOUBLE
# ------------------------------------------------------------

for column in numeric_features:
    model_data = model_data.withColumn(
        column,
        F.col(column).cast("double")
    )

model_data = model_data.withColumn(
    LABEL,
    F.col(LABEL).cast("double")
)


# ------------------------------------------------------------
# 6. DETERMINE AVAILABLE YEARS
# ------------------------------------------------------------

available_years = [
    row["year"]
    for row in (
        model_data
        .select(F.col("year").cast("int").alias("year"))
        .filter(F.col("year").isNotNull())
        .distinct()
        .orderBy("year")
        .collect()
    )
]

if len(available_years) < 3:
    raise ValueError(
        "At least three years are required for "
        "training, validation, and testing."
    )

if (
    PREFERRED_VALIDATION_YEAR in available_years
    and PREFERRED_TEST_YEAR in available_years
):
    VALIDATION_YEAR = PREFERRED_VALIDATION_YEAR
    TEST_YEAR = PREFERRED_TEST_YEAR
else:
    VALIDATION_YEAR = available_years[-2]
    TEST_YEAR = available_years[-1]

print("\nAvailable years:", available_years)
print("Validation year:", VALIDATION_YEAR)
print("Test year:", TEST_YEAR)


# ------------------------------------------------------------
# 7. CREATE CHRONOLOGICAL DATA SPLITS
# ------------------------------------------------------------

train_data = (
    model_data
    .filter(F.col("year") < VALIDATION_YEAR)
    .cache()
)

validation_data = (
    model_data
    .filter(F.col("year") == VALIDATION_YEAR)
    .cache()
)

test_data = (
    model_data
    .filter(F.col("year") == TEST_YEAR)
    .cache()
)

train_rows = train_data.count()
validation_rows = validation_data.count()
test_rows = test_data.count()

print("\nTraining rows:", train_rows)
print("Validation rows:", validation_rows)
print("Test rows:", test_rows)

if train_rows == 0:
    raise ValueError("The training dataset is empty.")

if validation_rows == 0:
    raise ValueError("The validation dataset is empty.")

if test_rows == 0:
    raise ValueError("The test dataset is empty.")


# ------------------------------------------------------------
# 8. REMOVE FEATURES THAT ARE COMPLETELY NULL IN TRAINING
# ------------------------------------------------------------

non_null_counts_row = (
    train_data
    .select(
        *[
            F.count(F.col(column)).alias(column)
            for column in numeric_features
        ]
    )
    .first()
)

all_null_features = [
    column
    for column in numeric_features
    if non_null_counts_row[column] == 0
]

numeric_features = [
    column
    for column in numeric_features
    if column not in all_null_features
]

if all_null_features:
    print("\nRemoved all-null training features:")
    for column in all_null_features:
        print(" -", column)

print("\nFinal numeric feature count:", len(numeric_features))


# ------------------------------------------------------------
# 9. CREATE A REUSABLE REGRESSION PIPELINE
# ------------------------------------------------------------

def create_regression_pipeline(
    label_col,
    reg_param,
    elastic_net_param
):
    """
    elasticNetParam:
        0.0 = ridge penalty
        1.0 = lasso penalty

    regParam:
        0.0 = unregularized linear regression
        >0  = regularized regression
    """

    imputed_feature_names = [
        f"{column}_imputed"
        for column in numeric_features
    ]

    imputer = Imputer(
        inputCols=numeric_features,
        outputCols=imputed_feature_names,
        strategy="median"
    )

    indexers = [
        StringIndexer(
            inputCol=column,
            outputCol=f"{column}_index",
            handleInvalid="keep"
        )
        for column in categorical_features
    ]

    pipeline_stages = [
        imputer,
        *indexers
    ]

    encoded_feature_names = []

    if categorical_features:
        encoded_feature_names = [
            f"{column}_ohe"
            for column in categorical_features
        ]

        encoder = OneHotEncoder(
            inputCols=[
                f"{column}_index"
                for column in categorical_features
            ],
            outputCols=encoded_feature_names,
            handleInvalid="keep",
            dropLast=True
        )

        pipeline_stages.append(encoder)

    assembler = VectorAssembler(
        inputCols=(
            imputed_feature_names
            + encoded_feature_names
        ),
        outputCol="features",
        handleInvalid="keep"
    )

    regression = LinearRegression(
        featuresCol="features",
        labelCol=label_col,
        predictionCol="prediction",
        regParam=float(reg_param),
        elasticNetParam=float(elastic_net_param),
        fitIntercept=True,
        standardization=True,
        maxIter=1000,
        tol=1e-6,
        solver="auto"
    )

    pipeline_stages.extend([
        assembler,
        regression
    ])

    return Pipeline(stages=pipeline_stages)


# ------------------------------------------------------------
# 10. METRIC FUNCTION
# ------------------------------------------------------------

def evaluate_regression_model(
    fitted_model,
    data,
    label_col
):
    predictions = fitted_model.transform(data)

    metrics = {}

    for metric_name in ["rmse", "mae", "r2"]:
        evaluator = RegressionEvaluator(
            labelCol=label_col,
            predictionCol="prediction",
            metricName=metric_name
        )

        metrics[metric_name] = float(
            evaluator.evaluate(predictions)
        )

    return metrics, predictions


# ------------------------------------------------------------
# 11. DEFINE MODEL CANDIDATES
# ------------------------------------------------------------

model_candidates = [
    {
        "model_family": "SLR",
        "reg_param": 0.0,
        "elastic_net": 0.0
    }
]

for penalty in REGULARIZATION_GRID:
    model_candidates.append({
        "model_family": "Ridge",
        "reg_param": penalty,
        "elastic_net": 0.0
    })

for penalty in REGULARIZATION_GRID:
    model_candidates.append({
        "model_family": "Lasso",
        "reg_param": penalty,
        "elastic_net": 1.0
    })


# ------------------------------------------------------------
# 12. FIT CANDIDATES ON TRAINING DATA
#     AND EVALUATE ON VALIDATION DATA
# ------------------------------------------------------------

validation_results = []
candidate_models = {}

for candidate in model_candidates:
    model_family = candidate["model_family"]
    reg_param = candidate["reg_param"]
    elastic_net = candidate["elastic_net"]

    print(
        f"Fitting {model_family}: "
        f"regParam={reg_param}, "
        f"elasticNetParam={elastic_net}"
    )

    pipeline = create_regression_pipeline(
        label_col=LABEL,
        reg_param=reg_param,
        elastic_net_param=elastic_net
    )

    fitted_model = pipeline.fit(train_data)

    metrics, _ = evaluate_regression_model(
        fitted_model,
        validation_data,
        LABEL
    )

    model_key = (
        model_family,
        reg_param,
        elastic_net
    )

    candidate_models[model_key] = fitted_model

    validation_results.append({
        "model": model_family,
        "reg_param": float(reg_param),
        "elastic_net": float(elastic_net),
        "validation_rmse": metrics["rmse"],
        "validation_mae": metrics["mae"],
        "validation_r2": metrics["r2"]
    })


# ------------------------------------------------------------
# 13. DISPLAY ALL VALIDATION RESULTS
# ------------------------------------------------------------

validation_results_pd = (
    pd.DataFrame(validation_results)
    .sort_values(
        ["validation_rmse", "validation_mae"]
    )
    .reset_index(drop=True)
)

print("\nALL VALIDATION RESULTS")
display(validation_results_pd)


# ------------------------------------------------------------
# 14. SELECT THE BEST MODEL IN EACH FAMILY
# ------------------------------------------------------------

best_model_specs = {}

for model_family in ["SLR", "Ridge", "Lasso"]:
    family_results = validation_results_pd[
        validation_results_pd["model"] == model_family
    ]

    best_row = (
        family_results
        .sort_values("validation_rmse")
        .iloc[0]
        .to_dict()
    )

    best_model_specs[model_family] = best_row

best_specs_pd = pd.DataFrame(
    list(best_model_specs.values())
).sort_values("validation_rmse")

print("\nBEST VALIDATION MODEL FROM EACH FAMILY")
display(best_specs_pd)


# ------------------------------------------------------------
# 15. REFIT EACH SELECTED MODEL USING
#     TRAINING + VALIDATION DATA
# ------------------------------------------------------------

train_validation_data = (
    train_data
    .unionByName(validation_data)
    .cache()
)

print(
    "\nTraining + validation rows:",
    train_validation_data.count()
)

final_models = {}
test_prediction_sets = {}
test_results = []

for model_family, specification in best_model_specs.items():

    final_pipeline = create_regression_pipeline(
        label_col=LABEL,
        reg_param=specification["reg_param"],
        elastic_net_param=specification["elastic_net"]
    )

    fitted_final_model = final_pipeline.fit(
        train_validation_data
    )

    metrics, predictions = evaluate_regression_model(
        fitted_final_model,
        test_data,
        LABEL
    )

    final_models[model_family] = fitted_final_model
    test_prediction_sets[model_family] = predictions

    test_results.append({
        "model": model_family,
        "reg_param": float(
            specification["reg_param"]
        ),
        "elastic_net": float(
            specification["elastic_net"]
        ),
        "test_rmse": metrics["rmse"],
        "test_mae": metrics["mae"],
        "test_r2": metrics["r2"]
    })


# ------------------------------------------------------------
# 16. DISPLAY FINAL TEST RESULTS
# ------------------------------------------------------------

test_results_pd = (
    pd.DataFrame(test_results)
    .sort_values(
        ["test_rmse", "test_mae"]
    )
    .reset_index(drop=True)
)

print("\nFINAL TEST RESULTS")
display(test_results_pd)


# ------------------------------------------------------------
# 17. CREATE A COMBINED TEST PREDICTION TABLE
# ------------------------------------------------------------

available_identifier_columns = [
    column
    for column in identifier_columns
    if column in model_data.columns
]

slr_predictions = (
    test_prediction_sets["SLR"]
    .select(
        *available_identifier_columns,
        LABEL,
        F.col("prediction").alias("slr_prediction")
    )
)

ridge_predictions = (
    test_prediction_sets["Ridge"]
    .select(
        *[
            column
            for column in [
                "year",
                "session_number",
                "driver_number"
            ]
            if column in model_data.columns
        ],
        F.col("prediction").alias("ridge_prediction")
    )
)

lasso_predictions = (
    test_prediction_sets["Lasso"]
    .select(
        *[
            column
            for column in [
                "year",
                "session_number",
                "driver_number"
            ]
            if column in model_data.columns
        ],
        F.col("prediction").alias("lasso_prediction")
    )
)

prediction_join_columns = [
    column
    for column in [
        "year",
        "session_number",
        "driver_number"
    ]
    if column in model_data.columns
]

all_test_predictions = (
    slr_predictions
    .join(
        ridge_predictions,
        on=prediction_join_columns,
        how="inner"
    )
    .join(
        lasso_predictions,
        on=prediction_join_columns,
        how="inner"
    )
    .withColumn(
        "slr_absolute_error",
        F.abs(
            F.col(LABEL)
            - F.col("slr_prediction")
        )
    )
    .withColumn(
        "ridge_absolute_error",
        F.abs(
            F.col(LABEL)
            - F.col("ridge_prediction")
        )
    )
    .withColumn(
        "lasso_absolute_error",
        F.abs(
            F.col(LABEL)
            - F.col("lasso_prediction")
        )
    )
)

print("\nTEST PREDICTIONS")

all_test_predictions.orderBy(
    "year",
    "session_number",
    LABEL
).show(
    100,
    truncate=False
)


# ------------------------------------------------------------
# 18. EXTRACT LASSO-SELECTED PREDICTORS
# ------------------------------------------------------------

lasso_pipeline_model = final_models["Lasso"]
lasso_regression_model = lasso_pipeline_model.stages[-1]

lasso_coefficients_array = (
    lasso_regression_model
    .coefficients
    .toArray()
)

# Transform one row so the features column contains metadata.
lasso_transformed_sample = (
    lasso_pipeline_model
    .transform(train_validation_data.limit(1))
)

features_metadata = (
    lasso_transformed_sample
    .schema["features"]
    .metadata
)

feature_names = []

try:
    attribute_groups = (
        features_metadata["ml_attr"]["attrs"]
    )

    feature_attributes = []

    for attribute_type in [
        "numeric",
        "binary",
        "nominal"
    ]:
        feature_attributes.extend(
            attribute_groups.get(
                attribute_type,
                []
            )
        )

    feature_attributes = sorted(
        feature_attributes,
        key=lambda attribute: attribute["idx"]
    )

    feature_names = [
        attribute["name"]
        for attribute in feature_attributes
    ]

except Exception:
    feature_names = [
        f"feature_{index}"
        for index in range(
            len(lasso_coefficients_array)
        )
    ]

# Metadata occasionally omits a feature.
if len(feature_names) != len(lasso_coefficients_array):
    feature_names = [
        f"feature_{index}"
        for index in range(
            len(lasso_coefficients_array)
        )
    ]

lasso_coefficients_pd = pd.DataFrame({
    "predictor": feature_names,
    "coefficient": lasso_coefficients_array
})

lasso_coefficients_pd["absolute_coefficient"] = (
    lasso_coefficients_pd["coefficient"].abs()
)

lasso_coefficients_pd["selected"] = (
    lasso_coefficients_pd["absolute_coefficient"]
    > LASSO_SELECTION_TOLERANCE
)

lasso_coefficients_pd["clean_predictor"] = (
    lasso_coefficients_pd["predictor"]
    .str.replace(
        "_imputed$",
        "",
        regex=True
    )
)

selected_lasso_predictors = (
    lasso_coefficients_pd[
        lasso_coefficients_pd["selected"]
    ]
    .sort_values(
        "absolute_coefficient",
        ascending=False
    )
    .reset_index(drop=True)
)

removed_lasso_predictors = (
    lasso_coefficients_pd[
        ~lasso_coefficients_pd["selected"]
    ]
    .sort_values("predictor")
    .reset_index(drop=True)
)

print("\nLASSO FEATURE-SELECTION SUMMARY")
print(
    "Total encoded predictors:",
    len(lasso_coefficients_pd)
)
print(
    "Selected predictors:",
    len(selected_lasso_predictors)
)
print(
    "Removed predictors:",
    len(removed_lasso_predictors)
)

print("\nLASSO-SELECTED PREDICTORS")
display(
    selected_lasso_predictors[
        [
            "clean_predictor",
            "predictor",
            "coefficient",
            "absolute_coefficient"
        ]
    ]
)

print("\nPREDICTORS REMOVED BY LASSO")
display(
    removed_lasso_predictors[
        [
            "clean_predictor",
            "predictor",
            "coefficient"
        ]
    ]
)


# ------------------------------------------------------------
# 19. SHOW ONLY SELECTED NUMERIC PREDICTORS
# ------------------------------------------------------------

selected_numeric_lasso_predictors = (
    selected_lasso_predictors[
        ~selected_lasso_predictors[
            "predictor"
        ].str.startswith(
            tuple(
                f"{column}_ohe"
                for column in categorical_features
            )
        )
    ]
    .reset_index(drop=True)
)

print("\nSELECTED NUMERIC LASSO PREDICTORS")
display(
    selected_numeric_lasso_predictors[
        [
            "clean_predictor",
            "coefficient",
            "absolute_coefficient"
        ]
    ]
)


# ------------------------------------------------------------
# 20. CLEANUP CACHED DATA
# ------------------------------------------------------------

train_data.unpersist()
validation_data.unpersist()
test_data.unpersist()
train_validation_data.unpersist()

Source table: formula1.driver_race_modeling_with_ratings
Total rows: 1889
Total columns: 57

Numeric features found: 49
Categorical features found: ['team_name']

Available years: [2020, 2021, 2022, 2023, 2025, 2026]
Validation year: 2025
Test year: 2026

Training rows: 1266
Validation rows: 472
Test rows: 151

Final numeric feature count: 49
Fitting SLR: regParam=0.0, elasticNetParam=0.0

26/07/11 01:35:36 WARN Instrumentation: [23adbff5] regParam is zero, which might cause numerical instability and overfitting.
26/07/11 01:35:36 WARN Instrumentation: [23adbff5] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.

Fitting Ridge: regParam=0.0001, elasticNetParam=0.0
Fitting Ridge: regParam=0.001, elasticNetParam=0.0
Fitting Ridge: regParam=0.01, elasticNetParam=0.0
Fitting Ridge: regParam=0.1, elasticNetParam=0.0
Fitting Ridge: regParam=1.0, elasticNetParam=0.0
Fitting Ridge: regParam=10.0, elasticNetParam=0.0
Fitting Lasso: regParam=0.0001, elasticNetParam=1.0
Fitting Lasso: regParam=0.001, elasticNetParam=1.0
Fitting Lasso: regParam=0.01, elasticNetParam=1.0
Fitting Lasso: regParam=0.1, elasticNetParam=1.0
Fitting Lasso: regParam=1.0, elasticNetParam=1.0
Fitting Lasso: regParam=10.0, elasticNetParam=1.0

ALL VALIDATION RESULTS

,model,reg_param,elastic_net,validation_rmse,validation_mae,validation_r2
0,Lasso,0.1000,1.0,4.330627,3.449685,0.429997
1,Ridge,1.0000,0.0,4.426922,3.512299,0.404366
2,Ridge,10.0000,0.0,4.437643,3.544759,0.401478
3,Lasso,1.0000,1.0,4.462235,3.666109,0.394826
4,Lasso,0.0100,1.0,4.491721,3.590863,0.386802
5,Ridge,0.1000,0.0,4.522806,3.596197,0.378285
6,Ridge,0.0100,0.0,4.587448,3.631775,0.360386
7,Lasso,0.0010,1.0,4.601048,3.641025,0.356588
8,Lasso,0.0001,1.0,4.601598,3.637955,0.356434
9,Ridge,0.0010,0.0,4.606297,3.642265,0.355119
10,Ridge,0.0001,0.0,4.609640,3.644944,0.354183
11,SLR,0.0000,0.0,4.614005,3.650981,0.352959
12,Lasso,10.0000,1.0,5.736388,4.969469,-0.000121

BEST VALIDATION MODEL FROM EACH FAMILY

,model,reg_param,elastic_net,validation_rmse,validation_mae,validation_r2
2,Lasso,0.1,1.0,4.330627,3.449685,0.429997
1,Ridge,1.0,0.0,4.426922,3.512299,0.404366
0,SLR,0.0,0.0,4.614005,3.650981,0.352959

Training + validation rows: 1738

26/07/11 01:35:46 WARN Instrumentation: [c18014e1] regParam is zero, which might cause numerical instability and overfitting.
26/07/11 01:35:46 WARN Instrumentation: [c18014e1] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.

FINAL TEST RESULTS

   model  reg_param  elastic_net  test_rmse  test_mae   test_r2
0  Lasso        0.1          1.0   5.273307  4.144121  0.314528
1    SLR        0.0          0.0   5.356508  3.975632  0.292727
2  Ridge        1.0          0.0   5.389450  4.283536  0.284001

TEST PREDICTIONS
+----+--------------+-------------+--------------+-----------------+----------------------+---------------+---------------+------------------+------------------+------------------+-------------------+--------------------+--------------------+
|year|session_number|driver_number|driver_id     |driver_name      |normalized_driver_name|team_name      |target_position|slr_prediction    |ridge_prediction  |lasso_prediction  |slr_absolute_error |ridge_absolute_error|lasso_absolute_error|
+----+--------------+-------------+--------------+-----------------+----------------------+---------------+---------------+------------------+------------------+------------------+-------------------+--------------------+--------------------+
|2026|1.0           |63           |russell       |George Russell   |george russell        |Mercedes       |1.0            |4.748925556779383 |4.145190582593475 |4.54000581380839  |3.7489255567793833 |3.145190582593475   |3.5400058138083903  |
|2026|1.0           |12           |antonelli     |Kimi Antonelli   |andrea kimi antonelli |Mercedes       |2.0            |5.608069527591304 |5.624246939481607 |5.917864758641203 |3.6080695275913044 |3.6242469394816066  |3.917864758641203   |
|2026|1.0           |16           |leclerc       |Charles Leclerc  |charles leclerc       |Ferrari        |3.0            |6.936747138282925 |6.251072496938316 |6.6287350426775316|3.936747138282925  |3.251072496938316   |3.6287350426775316  |
|2026|1.0           |44           |hamilton      |Lewis Hamilton   |lewis hamilton        |Ferrari        |4.0            |8.103575533709527 |8.09786614580814  |8.150837640870016 |4.103575533709527  |4.0978661458081405  |4.150837640870016   |
|2026|1.0           |1            |norris        |Lando Norris     |lando norris          |McLaren        |5.0            |7.46090359286886  |5.875505180435321 |6.661608323490761 |2.46090359286886   |0.8755051804353213  |1.6616083234907606  |
|2026|1.0           |87           |bearman       |Oliver Bearman   |oliver bearman        |Haas F1 Team   |7.0            |11.36358620774461 |11.947562911631852|11.692090966472433|4.363586207744611  |4.947562911631852   |4.692090966472433   |
|2026|1.0           |41           |arvid_lindblad|Arvid Lindblad   |arvid lindblad        |Racing Bulls   |8.0            |12.687616868807936|12.106247668716255|12.059770854620048|4.687616868807936  |4.1062476687162555  |4.059770854620048   |
|2026|1.0           |5            |bortoleto     |Gabriel Bortoleto|gabriel bortoleto     |Audi           |9.0            |9.893930232465735 |10.450168988592331|11.083522854902462|0.8939302324657348 |1.4501689885923312  |2.083522854902462   |
|2026|1.0           |10           |gasly         |Pierre Gasly     |pierre gasly          |Alpine         |10.0           |12.290749056041179|12.737140884655219|12.794994769424406|2.2907490560411787 |2.7371408846552185  |2.794994769424406   |
|2026|1.0           |31           |ocon          |Esteban Ocon     |esteban ocon          |Haas F1 Team   |11.0           |11.620819684829808|12.184919731051302|11.945704167679452|0.620819684829808  |1.184919731051302   |0.9457041676794518  |
|2026|1.0           |23           |albon         |Alexander Albon  |alexander albon       |Williams       |12.0           |12.142718376026693|12.539429991700835|12.913448567726297|0.1427183760266928 |0.5394299917008354  |0.9134485677262969  |
|2026|1.0           |30           |lawson        |Liam Lawson      |liam lawson           |Racing Bulls   |13.0           |11.204832414777762|10.85129718845518 |10.793317829149661|1.795167585222238  |2.148702811544821   |2.206682170850339   |
|2026|1.0           |43           |colapinto     |Franco Colapinto |franco colapinto      |Alpine         |14.0           |14.199380134076101|14.938576251555144|15.369045661719365|0.199380134076101  |0.9385762515551441  |1.3690456617193654  |
|2026|1.0           |11           |perez         |Sergio Perez     |sergio perez          |Cadillac       |16.0           |11.980131582295854|12.613659724210068|13.623879983378853|4.019868417704146  |3.386340275789932   |2.3761200166211474  |
|2026|1.0           |14           |alonso        |Fernando Alonso  |fernando alonso       |Aston Martin   |18.0           |10.929363627305108|11.284547262604747|12.362330414548001|7.070636372694892  |6.715452737395253   |5.637669585451999   |
|2026|1.0           |77           |bottas        |Valtteri Bottas  |valtteri bottas       |Cadillac       |19.0           |11.780870178412464|13.315645730558877|14.3623430267796  |7.219129821587536  |5.684354269441123   |4.6376569732204     |
|2026|1.0           |6            |hadjar        |Isack Hadjar     |isack hadjar          |Red Bull Racing|20.0           |7.154050407406885 |6.282345893698924 |6.5539494725515794|12.845949592593115 |13.717654106301076  |13.44605052744842   |
|2026|1.0           |81           |piastri       |Oscar Piastri    |oscar piastri         |McLaren        |21.0           |7.5295453082998165|5.893517272555468 |6.517855507345155 |13.470454691700184 |15.106482727444533  |14.482144492654845  |
|2026|1.0           |27           |hulkenberg    |Nico Hulkenberg  |nico hulkenberg       |Audi           |22.0           |9.412526133616318 |10.382932326548199|10.727113477852107|12.587473866383682 |11.617067673451801  |11.272886522147893  |
|2026|2.0           |12           |antonelli     |Kimi Antonelli   |andrea kimi antonelli |Mercedes       |1.0            |2.785146172158953 |5.456450669636605 |5.099743108079961 |1.785146172158953  |4.456450669636605   |4.099743108079961   |
|2026|2.0           |63           |russell       |George Russell   |george russell        |Mercedes       |2.0            |2.568475123416487 |4.8569457200001995|4.665628972007585 |0.5684751234164871 |2.8569457200001995  |2.6656289720075854  |
|2026|2.0           |44           |hamilton      |Lewis Hamilton   |lewis hamilton        |Ferrari        |3.0            |4.6574103584063025|7.275302300463525 |6.621199596779238 |1.6574103584063025 |4.275302300463525   |3.6211995967792383  |
|2026|2.0           |16           |leclerc       |Charles Leclerc  |charles leclerc       |Ferrari        |4.0            |4.8306314229063645|6.654661964235495 |6.463782381371788 |0.8306314229063645 |2.654661964235495   |2.4637823813717876  |
|2026|2.0           |87           |bearman       |Oliver Bearman   |oliver bearman        |Haas F1 Team   |5.0            |10.337758410021326|11.125845396253936|10.891279862952807|5.337758410021326  |6.125845396253936   |5.891279862952807   |
|2026|2.0           |10           |gasly         |Pierre Gasly     |pierre gasly          |Alpine         |6.0            |8.387060531286984 |10.125333704949814|9.843329247525253 |2.387060531286984  |4.1253337049498136  |3.8433292475252525  |
|2026|2.0           |30           |lawson        |Liam Lawson      |liam lawson           |Racing Bulls   |7.0            |13.604119135957134|13.350008021866001|12.95610687525276 |6.604119135957134  |6.350008021866001   |5.956106875252759   |
|2026|2.0           |6            |hadjar        |Isack Hadjar     |isack hadjar          |Red Bull Racing|8.0            |9.444943780531652 |8.716150988097626 |8.892590322629804 |1.444943780531652  |0.7161509880976258  |0.892590322629804   |
|2026|2.0           |55           |sainz         |Carlos Sainz     |carlos sainz          |Williams       |9.0            |15.256684252881033|13.725093231430817|13.611649932060807|6.256684252881033  |4.725093231430817   |4.611649932060807   |
|2026|2.0           |43           |colapinto     |Franco Colapinto |franco colapinto      |Alpine         |10.0           |12.68285829770862 |13.633703925652597|13.470298812991631|2.68285829770862   |3.633703925652597   |3.470298812991631   |
|2026|2.0           |27           |hulkenberg    |Nico Hulkenberg  |nico hulkenberg       |Audi           |11.0           |11.314699456816541|12.052971224698425|11.815862992104377|0.3146994568165411 |1.0529712246984246  |0.8158629921043765  |
|2026|2.0           |41           |arvid_lindblad|Arvid Lindblad   |arvid lindblad        |Racing Bulls   |12.0           |15.433449651841551|14.095360614856654|14.373536807119564|3.433449651841551  |2.095360614856654   |2.3735368071195637  |
|2026|2.0           |77           |bottas        |Valtteri Bottas  |valtteri bottas       |Cadillac       |13.0           |17.062176573207   |15.145236369048332|15.778199119631713|4.062176573207001  |2.145236369048332   |2.7781991196317133  |
|2026|2.0           |31           |ocon          |Esteban Ocon     |esteban ocon          |Haas F1 Team   |14.0           |12.30819553450457 |12.723230242164497|12.101979298178158|1.69180446549543   |1.2767697578355026  |1.8980207018218422  |
|2026|2.0           |11           |perez         |Sergio Perez     |sergio perez          |Cadillac       |15.0           |18.033430215191256|15.080076352761218|15.92645102732728 |3.033430215191256  |0.0800763527612176  |0.9264510273272801  |
|2026|2.0           |3            |max_verstappen|Max Verstappen   |max verstappen        |Red Bull Racing|16.0           |8.303238930454025 |7.951677386326901 |7.8408888207935   |7.696761069545975  |8.048322613673099   |8.1591111792065     |
|2026|2.0           |14           |alonso        |Fernando Alonso  |fernando alonso       |Aston Martin   |17.0           |15.401756334583993|13.329851869195616|13.915865316681176|1.5982436654160068 |3.6701481308043835  |3.0841346833188243  |
|2026|2.0           |18           |stroll        |Lance Stroll     |lance stroll          |Aston Martin   |18.0           |17.54248348899764 |15.191922908420235|16.283550745269302|0.45751651100236046|2.808077091579765   |1.7164492547306978  |
|2026|2.0           |81           |piastri       |Oscar Piastri    |oscar piastri         |McLaren        |19.0           |6.087940981483666 |6.794799128948821 |6.912623260800171 |12.912059018516334 |12.20520087105118   |12.08737673919983   |
|2026|2.0           |1            |norris        |Lando Norris     |lando norris          |McLaren        |20.0           |6.224529414182207 |6.577352170669035 |6.821298566432558 |13.775470585817793 |13.422647829330966  |13.178701433567442  |
|2026|2.0           |5            |bortoleto     |Gabriel Bortoleto|gabriel bortoleto     |Audi           |21.0           |13.726764119400617|13.390649165629103|13.803811467572391|7.273235880599383  |7.609350834370897   |7.196188532427609   |
|2026|2.0           |23           |albon         |Alexander Albon  |alexander albon       |Williams       |22.0           |15.047872840134296|14.18750398569091 |14.112118085360459|6.952127159865704  |7.81249601430909    |7.887881914639541   |
|2026|3.0           |12           |antonelli     |Kimi Antonelli   |andrea kimi antonelli |Mercedes       |1.0            |2.873783290875668 |5.177257991091674 |4.919071290872333 |1.873783290875668  |4.177257991091674   |3.919071290872333   |
|2026|3.0           |81           |piastri       |Oscar Piastri    |oscar piastri         |McLaren        |2.0            |4.450050337063544 |6.334424533218391 |6.390739641124892 |2.4500503370635442 |4.334424533218391   |4.390739641124892   |
|2026|3.0           |16           |leclerc       |Charles Leclerc  |charles leclerc       |Ferrari        |3.0            |5.227484553081254 |6.83628245568139  |6.440328873314696 |2.227484553081254  |3.83628245568139    |3.440328873314696   |
|2026|3.0           |63           |russell       |George Russell   |george russell        |Mercedes       |4.0            |2.669022911696363 |4.640073625547847 |4.578464794155108 |1.3309770883036371 |0.6400736255478474  |0.5784647941551082  |
|2026|3.0           |1            |norris        |Lando Norris     |lando norris          |McLaren        |5.0            |6.116659729371726 |7.025611681177544 |7.127284148351066 |1.116659729371726  |2.025611681177544   |2.127284148351066   |
|2026|3.0           |44           |hamilton      |Lewis Hamilton   |lewis hamilton        |Ferrari        |6.0            |6.377914848751626 |7.79925268532072  |7.410327200545579 |0.37791484875162595|1.7992526853207202  |1.410327200545579   |
|2026|3.0           |10           |gasly         |Pierre Gasly     |pierre gasly          |Alpine         |7.0            |8.44773331386784  |9.719767806173149 |9.617280536521047 |1.4477333138678397 |2.7197678061731487  |2.617280536521047   |
|2026|3.0           |3            |max_verstappen|Max Verstappen   |max verstappen        |Red Bull Racing|8.0            |8.838823711033168 |9.038756335471877 |8.913780741271747 |0.838823711033168  |1.0387563354718772  |0.9137807412717471  |
|2026|3.0           |30           |lawson        |Liam Lawson      |liam lawson           |Racing Bulls   |9.0            |13.463323705773593|13.094008711306806|12.725596645959618|4.463323705773593  |4.094008711306806   |3.7255966459596177  |
|2026|3.0           |31           |ocon          |Esteban Ocon     |esteban ocon          |Haas F1 Team   |10.0           |11.689811533711527|12.104543633243471|11.788032912273108|1.6898115337115271 |2.1045436332434715  |1.788032912273108   |
|2026|3.0           |27           |hulkenberg    |Nico Hulkenberg  |nico hulkenberg       |Audi           |11.0           |11.489845143342905|12.049288273945379|12.07411098237251 |0.4898451433429045 |1.049288273945379   |1.0741109823725097  |
|2026|3.0           |6            |hadjar        |Isack Hadjar     |isack hadjar          |Red Bull Racing|12.0           |6.999535042803878 |7.822766031956077 |8.404979489778691 |5.000464957196122  |4.177233968043923   |3.5950205102213086  |
|2026|3.0           |5            |bortoleto     |Gabriel Bortoleto|gabriel bortoleto     |Audi           |13.0           |11.129493602492339|11.430204759552494|11.63135046943035 |1.8705063975076612 |1.5697952404475064  |1.36864953056965    |
|2026|3.0           |41           |arvid_lindblad|Arvid Lindblad   |arvid lindblad        |Racing Bulls   |14.0           |13.018031676512102|12.549418014152389|12.730444001945322|0.981968323487898  |1.4505819858476112  |1.2695559980546776  |
|2026|3.0           |55           |sainz         |Carlos Sainz     |carlos sainz          |Williams       |15.0           |14.598303720295249|13.377899437426741|13.334645782207314|0.4016962797047512 |1.6221005625732587  |1.6653542177926859  |
|2026|3.0           |43           |colapinto     |Franco Colapinto |franco colapinto      |Alpine         |16.0           |14.490430687835602|14.09558953125358 |14.277297585713166|1.5095693121643983 |1.9044104687464198  |1.7227024142868341  |
|2026|3.0           |11           |perez         |Sergio Perez     |sergio perez          |Cadillac       |17.0           |14.726995146549115|13.920519320616803|14.665934834674934|2.2730048534508853 |3.079480679383197   |2.3340651653250664  |
|2026|3.0           |14           |alonso        |Fernando Alonso  |fernando alonso       |Aston Martin   |18.0           |16.96747283484162 |14.188936017078827|14.825277735024194|1.0325271651583812 |3.8110639829211728  |3.174722264975806   |
|2026|3.0           |77           |bottas        |Valtteri Bottas  |valtteri bottas       |Cadillac       |19.0           |15.922631949519852|14.701465286816182|15.433886984847312|3.077368050480148  |4.298534713183818   |3.5661130151526876  |
|2026|3.0           |23           |albon         |Alexander Albon  |alexander albon       |Williams       |20.0           |14.859647479595491|14.240716210112806|14.168927369563885|5.140352520404509  |5.759283789887194   |5.831072630436115   |
|2026|3.0           |18           |stroll        |Lance Stroll     |lance stroll          |Aston Martin   |21.0           |18.61653240790242 |15.785392101639804|16.91347706601945 |2.383467592097581  |5.214607898360196   |4.08652293398055    |
|2026|3.0           |87           |bearman       |Oliver Bearman   |oliver bearman        |Haas F1 Team   |22.0           |14.579700947373514|13.544955239639492|13.638945735236822|7.420299052626486  |8.455044760360508   |8.361054264763178   |
|2026|4.0           |12           |antonelli     |Kimi Antonelli   |andrea kimi antonelli |Mercedes       |1.0            |2.721474086925909 |4.726073562214083 |4.59202564321156  |1.7214740869259089 |3.726073562214083   |3.59202564321156    |
|2026|4.0           |1            |norris        |Lando Norris     |lando norris          |McLaren        |2.0            |5.260302187539253 |6.496207787887498 |6.427738200906232 |3.260302187539253  |4.496207787887498   |4.427738200906232   |
|2026|4.0           |81           |piastri       |Oscar Piastri    |oscar piastri         |McLaren        |3.0            |6.624510101269944 |6.973018303851642 |7.275852432594119 |3.6245101012699443 |3.9730183038516422  |4.275852432594119   |
|2026|4.0           |63           |russell       |George Russell   |george russell        |Mercedes       |4.0            |4.8968819298861135|5.534936259460777 |5.516291018420201 |0.8968819298861135 |1.5349362594607774  |1.5162910184202012  |
|2026|4.0           |3            |max_verstappen|Max Verstappen   |max verstappen        |Red Bull Racing|5.0            |3.9802797240622034|6.204159649857007 |5.841833906128157 |1.0197202759377966 |1.204159649857007   |0.8418339061281568  |
|2026|4.0           |44           |hamilton      |Lewis Hamilton   |lewis hamilton        |Ferrari        |6.0            |6.953350031595633 |7.7805579210091524|7.224432862989456 |0.9533500315956331 |1.7805579210091524  |1.224432862989456   |
|2026|4.0           |43           |colapinto     |Franco Colapinto |franco colapinto      |Alpine         |7.0            |11.535031142334432|11.935882816638355|11.779892170138707|4.535031142334432  |4.935882816638355   |4.779892170138707   |
|2026|4.0           |16           |leclerc       |Charles Leclerc  |charles leclerc       |Ferrari        |8.0            |4.8594747600230725|6.444241235483623 |5.904500300435043 |3.1405252399769275 |1.5557587645163773  |2.0954996995649573  |
|2026|4.0           |55           |sainz         |Carlos Sainz     |carlos sainz          |Williams       |9.0            |13.667779424406245|12.9970503063274  |12.564434948374288|4.667779424406245  |3.9970503063274005  |3.564434948374288   |
|2026|4.0           |23           |albon         |Alexander Albon  |alexander albon       |Williams       |10.0           |14.329228658835895|13.902140659401931|13.430365148850004|4.329228658835895  |3.9021406594019314  |3.4303651488500044  |
|2026|4.0           |87           |bearman       |Oliver Bearman   |oliver bearman        |Haas F1 Team   |11.0           |12.38467804998399 |12.671777844787005|12.058849177239688|1.3846780499839895 |1.6717778447870053  |1.0588491772396882  |
|2026|4.0           |5            |bortoleto     |Gabriel Bortoleto|gabriel bortoleto     |Audi           |12.0           |16.819916028655705|14.74653478151793 |15.38144462511863 |4.819916028655705  |2.74653478151793    |3.3814446251186308  |
|2026|4.0           |31           |ocon          |Esteban Ocon     |esteban ocon          |Haas F1 Team   |13.0           |13.634431300087357|12.837400823791084|12.406737071069944|0.6344313000873569 |0.16259917620891606 |0.5932629289300557  |
|2026|4.0           |41           |arvid_lindblad|Arvid Lindblad   |arvid lindblad        |Racing Bulls   |14.0           |16.496538236754407|14.715110367521591|14.647855797938787|2.4965382367544073 |0.7151103675215911  |0.6478557979387869  |
|2026|4.0           |14           |alonso        |Fernando Alonso  |fernando alonso       |Aston Martin   |15.0           |14.629107101934565|13.43246004483165 |13.634650624060715|0.3708928980654349 |1.5675399551683498  |1.3653493759392852  |
|2026|4.0           |11           |perez         |Sergio Perez     |sergio perez          |Cadillac       |16.0           |15.855247966832074|14.376334633124632|15.122853915969982|0.14475203316792573|1.6236653668753682  |0.8771460840300183  |

,clean_predictor,predictor,coefficient,absolute_coefficient
0,team_name_ohe_Red Bull Racing,team_name_ohe_Red Bull Racing,-0.689767,0.689767
1,team_name_ohe_Mercedes,team_name_ohe_Mercedes,-0.616033,0.616033
2,qualifying_position,qualifying_position_imputed,0.370588,0.370588
3,team_name_ohe_Renault,team_name_ohe_Renault,-0.231162,0.231162
4,team_name_ohe_McLaren,team_name_ohe_McLaren,-0.230693,0.230693
5,team_name_ohe_Racing Bulls,team_name_ohe_Racing Bulls,0.188446,0.188446
6,driver_rating,driver_rating_imputed,-0.129559,0.129559
7,team_average_finish_last_5,team_average_finish_last_5_imputed,0.082986,0.082986
8,average_positions_gained_last_5,average_positions_gained_last_5_imputed,0.081203,0.081203
9,team_name_ohe_Haas F1 Team,team_name_ohe_Haas F1 Team,0.079981,0.079981
10,team_average_finish_last_3,team_average_finish_last_3_imputed,0.043087,0.043087
11,previous_finish,previous_finish_imputed,0.029521,0.029521
12,teammate_qualifying_position,teammate_qualifying_position_imputed,0.025616,0.025616
13,team_name_ohe_Alpine,team_name_ohe_Alpine,0.013282,0.013282
14,qualifying_gap_to_pole,qualifying_gap_to_pole_imputed,-0.012439,0.012439
15,valid_qualifying_laps,valid_qualifying_laps_imputed,0.006842,0.006842
16,season_points_before_race,season_points_before_race_imputed,-0.002856,0.002856
17,session_number,session_number_imputed,0.002604,0.002604

PREDICTORS REMOVED BY LASSO

,clean_predictor,predictor,coefficient
0,average_finish_last_3,average_finish_last_3_imputed,0.0
1,average_finish_last_5,average_finish_last_5_imputed,0.0
2,average_gap_to_pole_last_5,average_gap_to_pole_last_5_imputed,0.0
3,average_points_last_5,average_points_last_5_imputed,0.0
4,average_qualifying_position_last_3,average_qualifying_position_last_3_imputed,0.0
5,average_qualifying_position_last_5,average_qualifying_position_last_5_imputed,0.0
6,best_qualifying_lap,best_qualifying_lap_imputed,0.0
7,career_races_before,career_races_before_imputed,0.0
8,dnf_rate_last_5,dnf_rate_last_5_imputed,0.0
9,finish_sd_last_5,finish_sd_last_5_imputed,0.0
10,maximum_finish_line_speed,maximum_finish_line_speed_imputed,0.0
11,maximum_speed_i1,maximum_speed_i1_imputed,0.0
12,maximum_speed_i2,maximum_speed_i2_imputed,0.0
13,maximum_speed_trap,maximum_speed_trap_imputed,0.0
14,mean_qualifying_lap,mean_qualifying_lap_imputed,0.0
15,median_qualifying_lap,median_qualifying_lap_imputed,0.0
16,previous_dnf,previous_dnf_imputed,0.0
17,previous_points,previous_points_imputed,0.0
18,qualified_top_10,qualified_top_10_imputed,0.0
19,qualifying_compounds,qualifying_compounds_imputed,0.0
20,qualifying_field_size,qualifying_field_size_imputed,0.0
21,qualifying_lap_sd,qualifying_lap_sd_imputed,0.0
22,qualifying_position_percentile,qualifying_position_percentile_imputed,0.0
23,qualifying_stints,qualifying_stints_imputed,0.0
24,qualifying_vs_teammate,qualifying_vs_teammate_imputed,0.0
25,race_air_temperature,race_air_temperature_imputed,0.0
26,race_humidity,race_humidity_imputed,0.0
27,race_max_air_temperature,race_max_air_temperature_imputed,0.0
28,race_max_wind_speed,race_max_wind_speed_imputed,0.0
29,race_min_air_temperature,race_min_air_temperature_imputed,0.0
30,race_pressure,race_pressure_imputed,0.0
31,race_rain_fraction,race_rain_fraction_imputed,0.0
32,race_rain,race_rain_imputed,0.0
33,race_track_temperature,race_track_temperature_imputed,0.0
34,race_wind_speed,race_wind_speed_imputed,0.0
35,team_average_points_last_5,team_average_points_last_5_imputed,0.0
36,team_dnf_rate_last_5,team_dnf_rate_last_5_imputed,0.0
37,team_name_ohe_Alfa Romeo,team_name_ohe_Alfa Romeo,0.0
38,team_name_ohe_Alfa Romeo Racing,team_name_ohe_Alfa Romeo Racing,0.0
39,team_name_ohe_AlphaTauri,team_name_ohe_AlphaTauri,0.0
40,team_name_ohe_Aston Martin,team_name_ohe_Aston Martin,0.0
41,team_name_ohe_Ferrari,team_name_ohe_Ferrari,0.0
42,team_name_ohe_Kick Sauber,team_name_ohe_Kick Sauber,0.0
43,team_name_ohe_Racing Point,team_name_ohe_Racing Point,0.0
44,team_name_ohe_Williams,team_name_ohe_Williams,0.0
45,team_name_ohe___unknown,team_name_ohe___unknown,0.0
46,total_points_last_5,total_points_last_5_imputed,0.0

SELECTED NUMERIC LASSO PREDICTORS

                    clean_predictor  coefficient  absolute_coefficient
0               qualifying_position     0.370588              0.370588
1                     driver_rating    -0.129559              0.129559
2        team_average_finish_last_5     0.082986              0.082986
3   average_positions_gained_last_5     0.081203              0.081203
4        team_average_finish_last_3     0.043087              0.043087
5                   previous_finish     0.029521              0.029521
6      teammate_qualifying_position     0.025616              0.025616
7            qualifying_gap_to_pole    -0.012439              0.012439
8             valid_qualifying_laps     0.006842              0.006842
9         season_points_before_race    -0.002856              0.002856
10                   session_number     0.002604              0.002604

DataFrame[year: int, normalized_driver_name: string, session_number: double, driver_number: string, driver_id: string, team_name: string, qualifying_position: double, qualifying_field_size: double, qualifying_position_percentile: double, qualified_top_10: double, teammate_qualifying_position: double, qualifying_vs_teammate: double, valid_qualifying_laps: double, best_qualifying_lap: double, median_qualifying_lap: double, mean_qualifying_lap: double, qualifying_lap_sd: double, qualifying_gap_to_pole: double, maximum_speed_i1: double, maximum_speed_i2: double, maximum_finish_line_speed: double, maximum_speed_trap: double, qualifying_stints: double, qualifying_compounds: double, average_qualifying_position_last_3: double, average_qualifying_position_last_5: double, average_gap_to_pole_last_5: double, race_air_temperature: double, race_track_temperature: double, race_humidity: double, race_pressure: double, race_wind_speed: double, race_max_wind_speed: double, race_min_air_temperature: double, race_max_air_temperature: double, race_rain: double, race_rain_fraction: double, previous_finish: double, previous_points: double, previous_dnf: double, average_finish_last_3: double, average_finish_last_5: double, finish_sd_last_5: double, average_points_last_5: double, total_points_last_5: double, dnf_rate_last_5: double, average_positions_gained_last_5: double, season_points_before_race: double, career_races_before: double, team_average_finish_last_3: double, team_average_finish_last_5: double, team_average_points_last_5: double, team_dnf_rate_last_5: double, target_position: double, target_championship_points: double, driver_name: string, driver_rating: double]